// Generated by scripts/sync-contract.mjs from the authenticated OGVCS-013 rc.1 authority.
// Contract manifest SHA-256: 4b4abe57a73f5e04dec184965a7d08130d5b311a6c745cc0dfb7728432fbc6dc

pub const CONTRACT_VERSION: &str = "0.1.0-rc.1";
pub const CONTRACT_MANIFEST_SHA256: &str =
    "4b4abe57a73f5e04dec184965a7d08130d5b311a6c745cc0dfb7728432fbc6dc";
pub const CONTRACT_ARTIFACT_SET_SHA256: &str =
    "bd43f2898b07d3545e1d3922d5a18632fb6d1fe95617d628b99a26aee184652b";
pub const PATH_CONTRACT_MANIFEST_SHA256: &str =
    "2f343e1dac238da527fbd36160419ec6fb53b780ac7e33c01e11acabbdd4782b";
pub const ERROR_REGISTRY_SHA256: &str =
    "a59ae4df8b91849bea4be1d855b7035b1f13bbc91a70b1fe8b93bf7e2555c893";
pub const GOLDEN_VECTORS_SHA256: &str =
    "f2dd8b02050738ce57b2b33989e0f14a8f8126916ba783f5b49f68f848320a1a";
