<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.0-rc.1</Version>
    <PackageId>OpenGameVcs.Protocol</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup><Compile Remove="Smoke/**/*.cs" /></ItemGroup>
</Project>
