BEGIN;

REVOKE ALL ON SCHEMA ogvcs_identity FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA ogvcs_identity FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA ogvcs_identity FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA ogvcs_identity FROM PUBLIC;

COMMIT;
