// Generated by scripts/sync-contract.mjs from the authenticated companion manifest.
// Contract manifest SHA-256: 07212333ce59e800c5311497d421a836a8896e5fdb9f1b78cbe8d92a6f9c3793

pub const CONTRACT_VERSION: &str = "0.1.0-rc.1";
pub const CONTRACT_MANIFEST_SHA256: &str =
    "07212333ce59e800c5311497d421a836a8896e5fdb9f1b78cbe8d92a6f9c3793";
pub const CONTRACT_ARTIFACT_SET_SHA256: &str =
    "da5a66f9c16933c95906540b400cd5694889643f1887936b674986a7b3f2640b";
pub const CONTRACT_VECTOR_SHA256: &str =
    "05cb39d185a9e49b2477e0036239b2df7183fcf5aa6e48e6d7c07a1419465484";
pub const RESULT_SCHEMA: &str = "ogvcs.cli-workspace/result/v1";
pub const CONFIG_SCHEMA: &str = "ogvcs.cli-workspace/config-resolution/v1";
pub const WORKSPACE_METADATA_SCHEMA: &str = "ogvcs.cli-workspace/workspace/v1";
pub const WORKSPACE_REPORT_SCHEMA: &str = "ogvcs.cli-workspace/workspace-report/v1";
pub const INITIALIZATION_SCHEMA: &str = "ogvcs.cli-workspace/initialization/v1";
pub const DIAGNOSTIC_SCHEMA: &str = "ogvcs.cli-workspace/diagnostic-preview/v1";

pub const EXIT_CODE_SUCCESS: i32 = 0;
pub const EXIT_CODE_INPUT: i32 = 2;
pub const EXIT_CODE_WORKSPACE: i32 = 3;
pub const EXIT_CODE_UNSUPPORTED: i32 = 4;
pub const EXIT_CODE_CANCELLED: i32 = 5;
pub const EXIT_CODE_INTERACTION_REQUIRED: i32 = 6;
pub const EXIT_CODE_UNAVAILABLE: i32 = 7;
pub const EXIT_CODE_INTERNAL: i32 = 70;

pub const EXIT_CLASS_CODES: &[(&str, i32)] = &[
    ("success", 0),
    ("input", 2),
    ("workspace", 3),
    ("unsupported", 4),
    ("cancelled", 5),
    ("interaction-required", 6),
    ("unavailable", 7),
    ("internal", 70),
];
