// Generated by scripts/sync-contract.mjs from the authenticated companion manifest.
// Contract manifest SHA-256: 44feed234a0d1f1f08aa729199f0d19ddb229e3bc2c1501e7cf5b01d1461f277

pub const CONTRACT_VERSION: &str = "0.2.0-rc.2";
pub const CONTRACT_MANIFEST_SHA256: &str =
    "44feed234a0d1f1f08aa729199f0d19ddb229e3bc2c1501e7cf5b01d1461f277";
pub const CONTRACT_ARTIFACT_SET_SHA256: &str =
    "085a83e34024c18e6a41f65c4dde7b0bcc1ccb10d51a1c890ba49f7b1770a948";
pub const CONTRACT_VECTOR_SHA256: &str =
    "1ea9278e70f7dcb17e0200d61c76a9ce93ce051090e2277867f3e7aa90885d98";
pub const RESULT_SCHEMA: &str = "ogvcs.cli-workspace/result/v1";
pub const CONFIG_SCHEMA: &str = "ogvcs.cli-workspace/config-resolution/v1";
pub const WORKSPACE_METADATA_SCHEMA: &str = "ogvcs.cli-workspace/workspace/v1";
pub const WORKSPACE_REPORT_SCHEMA: &str = "ogvcs.cli-workspace/workspace-report/v1";
pub const INITIALIZATION_SCHEMA: &str = "ogvcs.cli-workspace/initialization/v1";
pub const DIAGNOSTIC_SCHEMA: &str = "ogvcs.cli-workspace/diagnostic-preview/v1";

pub const EXIT_CODE_SUCCESS: i32 = 0;
pub const EXIT_CODE_INPUT: i32 = 2;
pub const EXIT_CODE_WORKSPACE: i32 = 3;
pub const EXIT_CODE_UNSUPPORTED: i32 = 4;
pub const EXIT_CODE_CANCELLED: i32 = 5;
pub const EXIT_CODE_INTERACTION_REQUIRED: i32 = 6;
pub const EXIT_CODE_UNAVAILABLE: i32 = 7;
pub const EXIT_CODE_INTERNAL: i32 = 70;

pub const EXIT_CLASS_CODES: &[(&str, i32)] = &[
    ("success", 0),
    ("input", 2),
    ("workspace", 3),
    ("unsupported", 4),
    ("cancelled", 5),
    ("interaction-required", 6),
    ("unavailable", 7),
    ("internal", 70),
];
