import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const crate = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const root = resolve(crate, '../../..');
const format = resolve(root, 'spec/repository-format/v1');
const target = resolve(crate, 'unicode');
const expectedSourceSha256 = '7570877e0fa197c45338f7c41a02636da4e14c8dba6a3611a01cd30bf329d5ca';
const compact = JSON.parse(await readFile(
  resolve(format, 'vectors/unicode/age-15.0.0-intervals.json'), 'utf8'
));
if (compact.schema !== 'ogvcs.repository-format.v1.unicode-age-intervals.v1' ||
    compact.unicodeVersion !== '15.0.0' || compact.intervalCount !== 715 ||
    compact.scalarCount !== 286_785 || compact.sourceSha256 !== expectedSourceSha256 ||
    compact.repertoire !==
      'Unicode scalar values whose Age is assigned in Unicode 15.0.0; surrogates excluded' ||
    !Array.isArray(compact.intervals) || compact.intervals.length !== 715) {
  throw new Error('invalid Unicode 15.0 compact authority');
}
let previousEnd = -1;
let scalarCount = 0;
for (const interval of compact.intervals) {
  if (!Array.isArray(interval) || interval.length !== 2 ||
      !Number.isSafeInteger(interval[0]) || !Number.isSafeInteger(interval[1]) ||
      interval[0] <= previousEnd || interval[0] < 0 || interval[0] > interval[1] ||
      interval[1] > 0x10ffff || (interval[0] <= 0xdfff && interval[1] >= 0xd800)) {
    throw new Error('invalid Unicode 15.0 interval');
  }
  scalarCount += interval[1] - interval[0] + 1;
  previousEnd = interval[1];
}
if (scalarCount !== compact.scalarCount) throw new Error('invalid Unicode 15.0 scalar count');

const generated = `// Generated by scripts/sync-unicode.mjs; do not edit.\n` +
  `// Unicode-DFS-2016 applies to the source data; see unicode/UNICODE-LICENSE.txt.\n` +
  `pub(crate) const UNICODE_15_INTERVALS: &[(u32, u32)] = &[\n` +
  compact.intervals.map(([start, end]) => `    (0x${start.toString(16)}, 0x${end.toString(16)}),`).join('\n') +
  `\n];\n`;
const files = [
  ['vectors/unicode/age-15.0.0-intervals.json', 'age-15.0.0-intervals.json'],
  ['unicode/DerivedAge-15.0.0.txt', 'DerivedAge-15.0.0.txt'],
  ['unicode/UNICODE-LICENSE.txt', 'UNICODE-LICENSE.txt'],
  ['unicode/NOTICE.md', 'NOTICE.md'],
];
const check = process.argv.includes('--check');
await mkdir(target, { recursive: true });
for (const [relative, name] of files) {
  const expected = await readFile(resolve(format, relative));
  const output = resolve(target, name);
  if (check) {
    const actual = await readFile(output).catch(() => undefined);
    if (!actual?.equals(expected)) throw new Error(`stale Unicode authority: ${name}`);
  } else {
    await writeFile(output, expected);
  }
}
const table = resolve(crate, 'src/unicode_age_table.rs');
if (check) {
  const actual = await readFile(table, 'utf8').catch(() => undefined);
  if (actual !== generated) throw new Error('stale generated Unicode interval table');
} else {
  await writeFile(table, generated);
}
