// Copyright (c) 2026 OpenGameVCS contributors. MIT licensed.
// @generated by foundation/protocol-baseline/codegen/generate.mjs; do not edit.
export type JsonValue = null | boolean | number | string | ReadonlyArray<JsonValue> | { readonly [key: string]: JsonValue };

export declare const CONTRACT_VERSION: "1.0.0-rc.1";
export declare const CONTRACT_MANIFEST_SHA256: "41bfebd0524458a669324e055c9849aff40f5a55bd5b8b47f1891516910ebffe";
export declare const PROTOCOL_VERSION: "ogvcs.control.https-json@1";
export declare const MESSAGE_SCHEMA_VERSION: "ogvcs.protocol.schema@1";
export declare const AUTHORIZATION_CONTRACT: "ogvcs.authorization@1";
export declare const PATH_CONTRACT: "ogvcs.path-filesystem@1";
export declare const PATH_PROFILE: "path.opengamevcs/portable@1";
export declare const REPOSITORY_FORMAT: "ogvcs.repository-format@1";

export interface ProtocolMessageDescriptor { readonly code: number; readonly name: string; readonly fieldCount: number; }
export interface ProtocolFieldDescriptor { readonly messageCode: number; readonly messageName: string; readonly wireName: string; readonly number: number; readonly normalizedType: string; readonly reference: string | null; readonly required: boolean; readonly presence: "required" | "optional"; readonly fingerprint: boolean; readonly sensitive: boolean; }
export declare const MESSAGE_DESCRIPTORS: ReadonlyArray<ProtocolMessageDescriptor>;
export declare const FIELD_DESCRIPTORS: ReadonlyArray<ProtocolFieldDescriptor>;

export interface CapabilityAxes {
  readonly protocolVersions: ReadonlyArray<string>;
  readonly schemaVersions: ReadonlyArray<string>;
  readonly repositoryFormats: ReadonlyArray<string>;
  readonly authorizationContracts: ReadonlyArray<string>;
  readonly pathContracts: ReadonlyArray<string>;
  readonly pathProfiles: ReadonlyArray<string>;
  readonly eventVersions: ReadonlyArray<string>;
  readonly transferProfiles: ReadonlyArray<string>;
  readonly extensions: ReadonlyArray<string>;
  readonly requiredCapabilities: ReadonlyArray<string>;
}

export interface NegotiationOffer {
  readonly schemaVersion: "ogvcs.protocol/negotiation-offer/v1";
  readonly clientNonce: string;
  readonly correlationId: string;
  readonly capabilities: CapabilityAxes;
  readonly deadlineUnixMs?: number;
}

export interface NegotiationSelection {
  readonly schemaVersion: "ogvcs.protocol/negotiation-selection/v1";
  readonly protocolVersion: "ogvcs.control.https-json@1";
  readonly messageSchemaVersion: "ogvcs.protocol.schema@1";
  readonly repositoryFormat: "ogvcs.repository-format@1";
  readonly authorizationContract: "ogvcs.authorization@1";
  readonly authorizationRegistrySha256: string;
  readonly pathContract: "ogvcs.path-filesystem@1";
  readonly pathProfile: "path.opengamevcs/portable@1";
  readonly pathRegistrySha256: string;
  readonly eventVersion: "ogvcs.events.base@1";
  readonly transferProfile: "ogvcs.transfer.range-resume-probe@1";
  readonly extensions: ReadonlyArray<string>;
  readonly protocolRegistrySetSha256: string;
  readonly repositoryRegistrySha256: string;
}

export interface NegotiationReceiptClaims {
  readonly schemaVersion: "ogvcs.protocol/negotiation-receipt-claims/v1";
  readonly selection: NegotiationSelection;
  readonly subjectDigest: string;
  readonly tenantDigest: string;
  readonly authorityEpoch: number;
  readonly sessionId: string;
  readonly clientNonce: string;
  readonly serverNonce: string;
  readonly issuedAtUnixMs: number;
  readonly expiresAtUnixMs: number;
}

export interface NegotiationReceipt {
  readonly algorithm: "HMAC-SHA-256";
  readonly keyId: string;
  readonly claims: NegotiationReceiptClaims;
  readonly mac: string;
}

export interface IdempotencyDescriptor {
  readonly key: string;
  readonly algorithm: "OGVCS-SEMANTIC-JCS-SHA-256";
  readonly projectionVersion: "ogvcs.protocol/fingerprint-projection@1";
  readonly fingerprint: string;
  readonly issuedAtUnixMs: number;
  readonly expiresAtUnixMs: number;
}

export interface RequestEnvelope {
  readonly schemaVersion: "ogvcs.protocol/request-envelope/v1";
  readonly operation: string;
  readonly correlationId: string;
  readonly deadlineUnixMs?: number;
  readonly negotiationReceipt: NegotiationReceipt;
  readonly idempotency?: IdempotencyDescriptor;
  readonly body: JsonValue;
  readonly extensions?: Readonly<Record<string, JsonValue>>;
}

export interface SafeParameter {
  readonly name: "conflictClass" | "gapClass" | "retryAfterMs";
  readonly value: string;
}

export interface ProblemDetails {
  readonly type: "https://errors.opengamevcs.dev/protocol/v1/protocol-malformed" | "https://errors.opengamevcs.dev/protocol/v1/protocol-limit-exceeded" | "https://errors.opengamevcs.dev/protocol/v1/protocol-unsupported" | "https://errors.opengamevcs.dev/protocol/v1/negotiation-no-common-version" | "https://errors.opengamevcs.dev/protocol/v1/negotiation-required-capability-unknown" | "https://errors.opengamevcs.dev/protocol/v1/negotiation-downgrade-rejected" | "https://errors.opengamevcs.dev/protocol/v1/negotiation-receipt-invalid" | "https://errors.opengamevcs.dev/protocol/v1/negotiation-receipt-expired" | "https://errors.opengamevcs.dev/protocol/v1/authorization-denied" | "https://errors.opengamevcs.dev/protocol/v1/idempotency-key-required" | "https://errors.opengamevcs.dev/protocol/v1/idempotency-key-reuse" | "https://errors.opengamevcs.dev/protocol/v1/cursor-invalid" | "https://errors.opengamevcs.dev/protocol/v1/cursor-scope-mismatch" | "https://errors.opengamevcs.dev/protocol/v1/cursor-expired" | "https://errors.opengamevcs.dev/protocol/v1/cursor-gap" | "https://errors.opengamevcs.dev/protocol/v1/stream-incomplete" | "https://errors.opengamevcs.dev/protocol/v1/stream-sequence-invalid" | "https://errors.opengamevcs.dev/protocol/v1/transfer-range-invalid" | "https://errors.opengamevcs.dev/protocol/v1/transfer-validator-mismatch" | "https://errors.opengamevcs.dev/protocol/v1/transfer-grant-invalid" | "https://errors.opengamevcs.dev/protocol/v1/redirect-forbidden" | "https://errors.opengamevcs.dev/protocol/v1/compression-forbidden" | "https://errors.opengamevcs.dev/protocol/v1/deadline-exceeded" | "https://errors.opengamevcs.dev/protocol/v1/cancelled" | "https://errors.opengamevcs.dev/protocol/v1/internal-error";
  readonly title: "Malformed protocol message" | "Protocol resource limit exceeded" | "Protocol profile unsupported" | "No compatible capability tuple" | "Required capability unavailable" | "Negotiation downgrade rejected" | "Negotiation receipt invalid" | "Negotiation receipt expired" | "Operation not authorized" | "Idempotency key required" | "Idempotency key input mismatch" | "Cursor invalid" | "Cursor scope mismatch" | "Cursor expired" | "Cursor retention gap" | "Stream terminated without completion" | "Stream sequence invalid" | "Transfer range invalid" | "Transfer validator mismatch" | "Transfer grant invalid" | "Redirect forbidden" | "Content coding forbidden" | "Deadline exceeded" | "Operation cancelled" | "Internal protocol error";
  readonly status: 400 | 413 | 426 | 409 | 401 | 403 | 410 | 502 | 416 | 412 | 415 | 504 | 408 | 500;
  readonly code: "PROTOCOL_MALFORMED" | "PROTOCOL_LIMIT_EXCEEDED" | "PROTOCOL_UNSUPPORTED" | "NEGOTIATION_NO_COMMON_VERSION" | "NEGOTIATION_REQUIRED_CAPABILITY_UNKNOWN" | "NEGOTIATION_DOWNGRADE_REJECTED" | "NEGOTIATION_RECEIPT_INVALID" | "NEGOTIATION_RECEIPT_EXPIRED" | "AUTHORIZATION_DENIED" | "IDEMPOTENCY_KEY_REQUIRED" | "IDEMPOTENCY_KEY_REUSE" | "CURSOR_INVALID" | "CURSOR_SCOPE_MISMATCH" | "CURSOR_EXPIRED" | "CURSOR_GAP" | "STREAM_INCOMPLETE" | "STREAM_SEQUENCE_INVALID" | "TRANSFER_RANGE_INVALID" | "TRANSFER_VALIDATOR_MISMATCH" | "TRANSFER_GRANT_INVALID" | "REDIRECT_FORBIDDEN" | "COMPRESSION_FORBIDDEN" | "DEADLINE_EXCEEDED" | "CANCELLED" | "INTERNAL_ERROR";
  readonly retryable: boolean;
  readonly correlationId: string;
  readonly parameters?: ReadonlyArray<SafeParameter>;
}

export interface ResponseEnvelope {
  readonly schemaVersion: "ogvcs.protocol/response-envelope/v1";
  readonly correlationId: string;
  readonly success: boolean;
  readonly body?: JsonValue;
  readonly problem?: ProblemDetails;
  readonly extensions?: Readonly<Record<string, JsonValue>>;
}

export interface Cursor {
  readonly token: string;
}

export interface PageEnvelope {
  readonly schemaVersion: "ogvcs.protocol/page-envelope/v1";
  readonly correlationId: string;
  readonly items: ReadonlyArray<JsonValue>;
  readonly state: "complete" | "more" | "gap";
  readonly nextCursor?: Cursor;
  readonly problem?: ProblemDetails;
}

export interface StreamFrame {
  readonly schemaVersion: "ogvcs.protocol/stream-frame/v1";
  readonly streamId: string;
  readonly sequence: number;
  readonly kind: "data" | "terminal" | "gap" | "cancelled" | "error";
  readonly payload?: JsonValue;
  readonly problem?: ProblemDetails;
}

export interface CompactTransferGrant {
  readonly scheme: "OGVCS-Grant";
  readonly representation: "request-root";
  readonly explicitObjectCount: number;
  readonly envelope: string;
  readonly authorizationManifestSha256: "3fb4dd4a89eb914f93a589b013bda8afcf4744c0d27171ee5849ca3b7bf62447";
}

export interface TransferProbe {
  readonly schemaVersion: "ogvcs.protocol/transfer-probe/v1";
  readonly operation: "probe" | "read" | "write";
  readonly grant: CompactTransferGrant;
  readonly resourceTag: string;
  readonly startOffset: number;
  readonly endOffsetExclusive?: number;
  readonly validatorTag?: string;
  readonly expectedSha256?: string;
  readonly contentEncoding: "identity";
  readonly followRedirects: false;
}

export interface TransferProbeResult {
  readonly schemaVersion: "ogvcs.protocol/transfer-probe-result/v1";
  readonly status: "complete" | "partial" | "interrupted" | "rejected";
  readonly acceptedStart: number;
  readonly acceptedEndExclusive: number;
  readonly totalBytes: number;
  readonly validatorTag: string;
  readonly contentSha256: string;
  readonly terminal: boolean;
  readonly problem?: ProblemDetails;
}

export interface ExtensionRegistration {
  readonly code: number;
  readonly id: string;
  readonly owner: string;
  readonly state: "candidate" | "ratified" | "deprecated" | "reserved";
  readonly requirement: "optional" | "required";
  readonly fallback: "ignore" | "reject";
  readonly securityImpact: string;
  readonly dataImpact: string;
  readonly affectedSchemas: ReadonlyArray<string>;
  readonly minimumProtocol: string;
}

export interface CompatibilityEntry {
  readonly code: number;
  readonly state: "candidate" | "ratified" | "deprecated";
  readonly selection: NegotiationSelection;
  readonly requiredCapabilities: ReadonlyArray<string>;
  readonly authorizationManifestSha256: string;
  readonly pathManifestSha256: string;
  readonly repositoryManifestSha256: string;
}

export interface RunnerHello {
  readonly schemaVersion: "ogvcs.protocol/runner-hello/v1";
  readonly adapterId: string;
  readonly contractManifestSha256: string;
  readonly operations: ReadonlyArray<"negotiate" | "validate-envelope" | "fingerprint" | "validate-cursor" | "validate-stream" | "transfer-probe" | "contract-load" | "runner-batch" | "release-preflight">;
}

export interface RunnerCase {
  readonly schemaVersion: "ogvcs.protocol/runner-case/v1";
  readonly id: string;
  readonly operation: "negotiate" | "validate-envelope" | "fingerprint" | "validate-cursor" | "validate-stream" | "transfer-probe" | "contract-load" | "runner-batch" | "release-preflight";
  readonly input: JsonValue;
  readonly inputKind: "semantic-value" | "raw-json" | "raw-bytes" | "jsonl";
  readonly configuredLimits?: RunnerConfiguredLimits;
  readonly control: RunnerExecutionControl;
  readonly serverContext?: JsonValue;
}

export interface RunnerResult {
  readonly schemaVersion: "ogvcs.protocol/runner-result/v1";
  readonly id: string;
  readonly result: "accept" | "reject";
  readonly code: "NONE" | "PROTOCOL_MALFORMED" | "PROTOCOL_LIMIT_EXCEEDED" | "PROTOCOL_UNSUPPORTED" | "NEGOTIATION_NO_COMMON_VERSION" | "NEGOTIATION_REQUIRED_CAPABILITY_UNKNOWN" | "NEGOTIATION_DOWNGRADE_REJECTED" | "NEGOTIATION_RECEIPT_INVALID" | "NEGOTIATION_RECEIPT_EXPIRED" | "AUTHORIZATION_DENIED" | "IDEMPOTENCY_KEY_REQUIRED" | "IDEMPOTENCY_KEY_REUSE" | "CURSOR_INVALID" | "CURSOR_SCOPE_MISMATCH" | "CURSOR_EXPIRED" | "CURSOR_GAP" | "STREAM_INCOMPLETE" | "STREAM_SEQUENCE_INVALID" | "TRANSFER_RANGE_INVALID" | "TRANSFER_VALIDATOR_MISMATCH" | "TRANSFER_GRANT_INVALID" | "REDIRECT_FORBIDDEN" | "COMPRESSION_FORBIDDEN" | "DEADLINE_EXCEEDED" | "CANCELLED" | "INTERNAL_ERROR";
  readonly preMutation: boolean;
  readonly mutationCount: number;
  readonly semanticDigest?: string;
  readonly traceDigest: string;
}

export interface RunnerReport {
  readonly schemaVersion: "ogvcs.protocol/runner-report/v1";
  readonly adapterId: string;
  readonly contractManifestSha256: string;
  readonly results: ReadonlyArray<RunnerResult>;
  readonly passed: number;
  readonly failed: number;
  readonly reportDigest: string;
}

export interface RunnerConfiguredLimits {
  readonly maxControlMessageBytes?: number;
  readonly maxCanonicalInputBytes?: number;
  readonly maxJsonDepth?: number;
  readonly maxJsonNodes?: number;
  readonly maxObjectMembers?: number;
  readonly maxArrayItems?: number;
  readonly maxStringUtf8Bytes?: number;
  readonly maxExtensionEntries?: number;
  readonly maxCapabilityItems?: number;
  readonly maxErrorParameters?: number;
  readonly maxPageItems?: number;
  readonly maxJsonlFrameBytes?: number;
  readonly maxJsonlFrames?: number;
  readonly maxCursorBytes?: number;
  readonly maxIdempotencyKeyBytes?: number;
  readonly maxReceiptBytes?: number;
  readonly maxGrantBytes?: number;
  readonly maxTransferRangeBytes?: number;
  readonly maxHeaderBytes?: number;
  readonly maxCorrelationIdBytes?: number;
  readonly maxOperationBytes?: number;
  readonly maxRunnerCases?: number;
  readonly maxSafeParameterBytes?: number;
  readonly maxDeadlineHorizonMs?: number;
  readonly maxReceiptLifetimeMs?: number;
  readonly maxCursorLifetimeMs?: number;
  readonly maxRegistryEntries?: number;
  readonly maxJsonKeyUtf8Bytes?: number;
  readonly maxJsonCollectionItems?: number;
  readonly maxJsonlStreamBytes?: number;
  readonly maxWorkingMemoryBytes?: number;
  readonly maxOperationTimeMs?: number;
  readonly maxSchemaEvaluationSteps?: number;
  readonly maxContractArtifacts?: number;
  readonly maxContractBytes?: number;
}

export interface RunnerExecutionControl {
  readonly cancellation: "none" | "before-operation" | "after-first-stream-frame";
  readonly clockSamplesUnixMs: ReadonlyArray<number>;
}

export interface RunnerPrincipal {
  readonly subjectDigest: string;
  readonly tenantDigest: string;
  readonly authorityEpoch: number;
  readonly sessionId: string;
}

export interface NegotiationCaseInput {
  readonly route: "negotiate" | "verify-receipt";
  readonly offer: NegotiationOffer;
  readonly serverSelection: NegotiationSelection;
  readonly principal: RunnerPrincipal;
  readonly verificationPrincipal: RunnerPrincipal;
  readonly minimumCapabilities: ReadonlyArray<string>;
  readonly transportScheme: "https" | "http";
  readonly tlsVersion: "1.3" | "1.2";
  readonly loopbackConformance: boolean;
  readonly receiptKeyId: string;
  readonly receiptKeyBase64url: string;
  readonly serverNonce: string;
  readonly issueAtUnixMs: number;
  readonly verifyAtUnixMs: number;
  readonly receiptMacXor: number;
  readonly receiptLifetimeMs: number;
  readonly verificationSelection: NegotiationSelection;
}

export interface EnvelopeCaseInput {
  readonly route: "validate-document" | "validate-extension" | "authorize" | "emit-problem";
  readonly targetSchema: "JsonValue" | "RequestEnvelope" | "ResponseEnvelope" | "ProblemDetails" | "PageEnvelope" | "NegotiationCaseInput" | "CursorCaseInput";
  readonly encoding: "semantic-json" | "raw-json" | "raw-hex";
  readonly document?: JsonValue;
  readonly rawInput?: string;
  readonly atUnixMs: number;
  readonly transportScheme: "https" | "http";
  readonly tlsVersion: "1.3" | "1.2";
  readonly method: "GET" | "POST";
  readonly contentEncoding: string;
  readonly redirectStatus?: number;
  readonly originChanged: boolean;
  readonly httpStatus?: number;
  readonly authorizationDecision: "allow" | "deny" | "error";
  readonly forwardedSubjectMatches: boolean;
  readonly forwardedTenantMatches: boolean;
  readonly allowSameOriginRedirect: boolean;
  readonly headers: ReadonlyArray<TransportHeaderInput>;
  readonly selectedExtensions: ReadonlyArray<string>;
  readonly rawInputUtf16CodeUnits?: ReadonlyArray<number>;
}

export interface FingerprintCaseInput {
  readonly route: "fingerprint" | "idempotency";
  readonly projections: ReadonlyArray<JsonValue>;
  readonly rawInputs: ReadonlyArray<string>;
  readonly algorithm: string;
  readonly idempotencyKey: string;
  readonly retryableMutation: boolean;
  readonly attemptProjectionIndexes: ReadonlyArray<number>;
  readonly attemptSchedule: ReadonlyArray<"fingerprint" | "begin-mutation" | "commit" | "lose-response" | "deadline" | "expire-key" | "retire-tombstone" | "retry">;
  readonly idempotencyIssuedAtUnixMs: number;
  readonly idempotencyExpiresAtUnixMs: number;
  readonly atUnixMs: number;
  readonly tombstoneRetentionMs: number;
  readonly attemptAuthorizationDecisions: ReadonlyArray<"allow" | "deny">;
}

export interface CursorCaseInput {
  readonly route: "validate-page" | "validate-token" | "token-lifecycle" | "token-byte-preflight";
  readonly page: JsonValue;
  readonly issueScope: JsonValue;
  readonly readScope: JsonValue;
  readonly issuedAtUnixMs: number;
  readonly readAtUnixMs: number;
  readonly ttlMs: number;
  readonly generation: number;
  readonly minimumRetainedGeneration: number;
  readonly tokenMutation: "none" | "tamper" | "unknown";
  readonly suppliedToken: string;
  readonly tokenSource: "issued" | "supplied";
  readonly lifecycleActions: ReadonlyArray<"issue" | "expire" | "issue-unrelated" | "prune" | "read">;
  readonly tombstoneRetentionMs: number;
}

export interface StreamCaseInput {
  readonly route: "parse" | "write-roundtrip";
  readonly encoding: "frames" | "jsonl";
  readonly frames: ReadonlyArray<JsonValue>;
  readonly jsonl: string;
  readonly sourceCloses: boolean;
}

export interface TransferCaseInput {
  readonly route: "probe" | "verify-grant" | "transport-policy" | "validate-result" | "http-range";
  readonly probe: JsonValue;
  readonly transportResponse: JsonValue;
  readonly grantLocation: "header" | "query";
  readonly responseStatus: number;
  readonly originChanged: boolean;
  readonly digestMatches: boolean;
  readonly logGrant: boolean;
  readonly proxyMode: "direct" | "connect";
  readonly proxyConfigured: boolean;
  readonly connectResult: "not-attempted" | "success" | "failure" | "bypassed";
  readonly certificateValid: boolean;
  readonly hostnameMatches: boolean;
  readonly probeResult?: JsonValue;
  readonly requestHeaders: ReadonlyArray<TransportHeaderInput>;
  readonly responseHeaders: ReadonlyArray<TransportHeaderInput>;
  readonly authorizationContext: JsonValue;
  readonly authorizationPublicJwk: JsonValue;
  readonly responseBodyHex: string;
}

export interface ContractArtifactInput {
  readonly path: string;
  readonly bytesHex: string;
}

export interface ContractLoadCaseInput {
  readonly route: "inventory" | "registry";
  readonly artifacts: ReadonlyArray<ContractArtifactInput>;
  readonly registryEntries: ReadonlyArray<JsonValue>;
}

export interface RunnerBatchEntry {
  readonly id: string;
  readonly operation: "negotiate" | "validate-envelope" | "fingerprint" | "validate-cursor" | "validate-stream" | "transfer-probe" | "contract-load" | "runner-batch" | "release-preflight";
}

export interface RunnerBatchCaseInput {
  readonly cases: ReadonlyArray<RunnerBatchEntry>;
}

export interface TraceHeader {
  readonly name: string;
  readonly value: string;
}

export interface TraceLogEntry {
  readonly event: string;
  readonly fields: Readonly<Record<string, JsonValue>>;
}

export interface AdapterTrace {
  readonly responseBody: JsonValue;
  readonly responseHeaders: ReadonlyArray<TraceHeader>;
  readonly streamFrames: ReadonlyArray<StreamFrame>;
  readonly logEntries: ReadonlyArray<TraceLogEntry>;
  readonly semanticOutput: JsonValue;
}

export interface AdapterResult {
  readonly schemaVersion: "ogvcs.protocol/adapter-result/v1";
  readonly id: string;
  readonly result: "accept" | "reject";
  readonly code: "NONE" | "PROTOCOL_MALFORMED" | "PROTOCOL_LIMIT_EXCEEDED" | "PROTOCOL_UNSUPPORTED" | "NEGOTIATION_NO_COMMON_VERSION" | "NEGOTIATION_REQUIRED_CAPABILITY_UNKNOWN" | "NEGOTIATION_DOWNGRADE_REJECTED" | "NEGOTIATION_RECEIPT_INVALID" | "NEGOTIATION_RECEIPT_EXPIRED" | "AUTHORIZATION_DENIED" | "IDEMPOTENCY_KEY_REQUIRED" | "IDEMPOTENCY_KEY_REUSE" | "CURSOR_INVALID" | "CURSOR_SCOPE_MISMATCH" | "CURSOR_EXPIRED" | "CURSOR_GAP" | "STREAM_INCOMPLETE" | "STREAM_SEQUENCE_INVALID" | "TRANSFER_RANGE_INVALID" | "TRANSFER_VALIDATOR_MISMATCH" | "TRANSFER_GRANT_INVALID" | "REDIRECT_FORBIDDEN" | "COMPRESSION_FORBIDDEN" | "DEADLINE_EXCEEDED" | "CANCELLED" | "INTERNAL_ERROR";
  readonly preMutation: boolean;
  readonly mutationCount: number;
  readonly trace: AdapterTrace;
}

export interface ReleaseAssignment {
  readonly kind: "message" | "field" | "limit" | "error" | "capability" | "extension";
  readonly scope: string;
  readonly name: string;
  readonly code: number;
  readonly semanticSha256: string;
}

export interface ReleasePreflightCaseInput {
  readonly proposedSelection: ReleaseSelectionProposal;
  readonly requiredCapabilities: ReadonlyArray<string>;
  readonly authorizationManifestSha256: string;
  readonly pathManifestSha256: string;
  readonly repositoryManifestSha256: string;
  readonly priorAssignmentSnapshotSha256: string;
  readonly proposedAssignments: ReadonlyArray<ReleaseAssignment>;
}

export interface ReleaseSelectionProposal {
  readonly schemaVersion: "ogvcs.protocol/release-selection-proposal/v1";
  readonly protocolVersion: string;
  readonly messageSchemaVersion: string;
  readonly repositoryFormat: string;
  readonly authorizationContract: string;
  readonly authorizationRegistrySha256: string;
  readonly pathContract: string;
  readonly pathProfile: string;
  readonly pathRegistrySha256: string;
  readonly eventVersion: string;
  readonly transferProfile: string;
  readonly extensions: ReadonlyArray<string>;
  readonly protocolRegistrySetSha256: string;
  readonly repositoryRegistrySha256: string;
}

export interface TransportHeaderInput {
  readonly name: string;
  readonly value: string;
}

export interface CursorScopeInput {
  readonly subject: string;
  readonly tenant: string;
  readonly repository: string;
  readonly operation: string;
  readonly queryDigest: string;
}

export interface IdempotencyProjectionInput {
  readonly schemaVersion: string;
  readonly operation: string;
  readonly body: JsonValue;
  readonly extensions: Readonly<Record<string, JsonValue>>;
}

export interface TransferProbeNonGrantInput {
  readonly schemaVersion: "ogvcs.protocol/transfer-probe-non-grant-input/v1";
  readonly operation: "probe" | "read" | "write";
  readonly resourceTag: string;
  readonly startOffset: number;
  readonly endOffsetExclusive?: number;
  readonly validatorTag?: string;
  readonly expectedSha256?: string;
  readonly contentEncoding: "identity";
  readonly followRedirects: false;
}

export declare const FIELD_ASSIGNMENTS: Readonly<Record<string, Readonly<{ messageCode: number; fields: Readonly<Record<string, number>> }>>>;
export declare const LIMITS: Readonly<Record<string, number>>;
export declare const ERROR_CODES: Readonly<Record<string, number>>;
