// Copyright (c) 2026 OpenGameVCS contributors. MIT licensed.
// @generated by foundation/protocol-baseline/codegen/generate.mjs; do not edit.
#pragma once
#include <array>
#include <cstddef>
#include <cstdint>
#include <map>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace opengamevcs::protocol::v1 {
inline constexpr const char* contract_version = "1.0.0-rc.1";
inline constexpr const char* contract_manifest_sha256 = "bc343842291040b6b0c2c941b183863500c4d60a4618256ffc6e36a1d6afbe72";
inline constexpr const char* protocol_version = "ogvcs.control.https-json@1";
inline constexpr const char* message_schema_version = "ogvcs.protocol.schema@1";
inline constexpr const char* authorization_contract = "ogvcs.authorization@1";
inline constexpr const char* path_contract = "ogvcs.path-filesystem@1";
inline constexpr const char* path_profile = "path.opengamevcs/portable@1";
inline constexpr const char* repository_format = "ogvcs.repository-format@1";

struct JsonValue {
  using array_type = std::vector<JsonValue>;
  using object_type = std::map<std::string, JsonValue>;
  std::variant<std::nullptr_t, bool, std::int64_t, std::string, array_type, object_type> value;
};

struct message_descriptor { std::uint16_t code; const char* name; std::size_t field_count; };
struct field_descriptor { std::uint16_t message_code; const char* message_name; const char* wire_name; std::uint16_t number; const char* normalized_type; const char* reference; bool required; const char* presence; bool fingerprint; bool sensitive; };

inline constexpr std::array<message_descriptor, 46> message_descriptors{{
  message_descriptor{1, "CapabilityAxes", 10},
  message_descriptor{2, "NegotiationOffer", 5},
  message_descriptor{3, "NegotiationSelection", 14},
  message_descriptor{4, "NegotiationReceiptClaims", 10},
  message_descriptor{5, "NegotiationReceipt", 4},
  message_descriptor{6, "IdempotencyDescriptor", 6},
  message_descriptor{7, "RequestEnvelope", 8},
  message_descriptor{8, "SafeParameter", 2},
  message_descriptor{9, "ProblemDetails", 7},
  message_descriptor{10, "ResponseEnvelope", 6},
  message_descriptor{11, "Cursor", 1},
  message_descriptor{12, "PageEnvelope", 6},
  message_descriptor{13, "StreamFrame", 6},
  message_descriptor{14, "CompactTransferGrant", 5},
  message_descriptor{15, "TransferProbe", 10},
  message_descriptor{16, "TransferProbeResult", 9},
  message_descriptor{17, "ExtensionRegistration", 10},
  message_descriptor{18, "CompatibilityEntry", 7},
  message_descriptor{19, "RunnerHello", 4},
  message_descriptor{20, "RunnerCase", 8},
  message_descriptor{21, "RunnerResult", 8},
  message_descriptor{22, "RunnerReport", 7},
  message_descriptor{23, "RunnerConfiguredLimits", 35},
  message_descriptor{24, "RunnerExecutionControl", 2},
  message_descriptor{25, "RunnerPrincipal", 4},
  message_descriptor{26, "NegotiationCaseInput", 17},
  message_descriptor{27, "EnvelopeCaseInput", 20},
  message_descriptor{28, "FingerprintCaseInput", 13},
  message_descriptor{29, "CursorCaseInput", 14},
  message_descriptor{30, "StreamCaseInput", 5},
  message_descriptor{31, "TransferCaseInput", 19},
  message_descriptor{32, "ContractArtifactInput", 2},
  message_descriptor{33, "ContractLoadCaseInput", 3},
  message_descriptor{34, "RunnerBatchEntry", 2},
  message_descriptor{35, "RunnerBatchCaseInput", 1},
  message_descriptor{36, "TraceHeader", 2},
  message_descriptor{37, "TraceLogEntry", 2},
  message_descriptor{38, "AdapterTrace", 5},
  message_descriptor{39, "AdapterResult", 7},
  message_descriptor{40, "ReleaseAssignment", 5},
  message_descriptor{41, "ReleasePreflightCaseInput", 7},
  message_descriptor{42, "ReleaseSelectionProposal", 14},
  message_descriptor{43, "TransportHeaderInput", 2},
  message_descriptor{44, "CursorScopeInput", 5},
  message_descriptor{45, "IdempotencyProjectionInput", 4},
  message_descriptor{46, "TransferProbeNonGrantInput", 9},
}};

inline constexpr std::array<field_descriptor, 352> field_descriptors{{
  field_descriptor{1, "CapabilityAxes", "protocolVersions", 1, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{1, "CapabilityAxes", "schemaVersions", 2, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{1, "CapabilityAxes", "repositoryFormats", 3, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{1, "CapabilityAxes", "authorizationContracts", 4, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{1, "CapabilityAxes", "pathContracts", 5, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{1, "CapabilityAxes", "pathProfiles", 6, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{1, "CapabilityAxes", "eventVersions", 7, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{1, "CapabilityAxes", "transferProfiles", 8, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{1, "CapabilityAxes", "extensions", 9, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{1, "CapabilityAxes", "requiredCapabilities", 10, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{2, "NegotiationOffer", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{2, "NegotiationOffer", "clientNonce", 2, "string", nullptr, true, "required", false, true},
  field_descriptor{2, "NegotiationOffer", "correlationId", 3, "string", nullptr, true, "required", false, false},
  field_descriptor{2, "NegotiationOffer", "capabilities", 4, "reference", "CapabilityAxes", true, "required", true, false},
  field_descriptor{2, "NegotiationOffer", "deadlineUnixMs", 5, "integer", nullptr, false, "optional", false, false},
  field_descriptor{3, "NegotiationSelection", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{3, "NegotiationSelection", "protocolVersion", 2, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{3, "NegotiationSelection", "messageSchemaVersion", 3, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{3, "NegotiationSelection", "repositoryFormat", 4, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{3, "NegotiationSelection", "authorizationContract", 5, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{3, "NegotiationSelection", "authorizationRegistrySha256", 6, "string", nullptr, true, "required", true, false},
  field_descriptor{3, "NegotiationSelection", "pathContract", 7, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{3, "NegotiationSelection", "pathProfile", 8, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{3, "NegotiationSelection", "pathRegistrySha256", 9, "string", nullptr, true, "required", true, false},
  field_descriptor{3, "NegotiationSelection", "eventVersion", 10, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{3, "NegotiationSelection", "transferProfile", 11, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{3, "NegotiationSelection", "extensions", 12, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{3, "NegotiationSelection", "protocolRegistrySetSha256", 13, "string", nullptr, true, "required", true, false},
  field_descriptor{3, "NegotiationSelection", "repositoryRegistrySha256", 14, "string", nullptr, true, "required", true, false},
  field_descriptor{4, "NegotiationReceiptClaims", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{4, "NegotiationReceiptClaims", "selection", 2, "reference", "NegotiationSelection", true, "required", true, false},
  field_descriptor{4, "NegotiationReceiptClaims", "subjectDigest", 3, "string", nullptr, true, "required", true, true},
  field_descriptor{4, "NegotiationReceiptClaims", "tenantDigest", 4, "string", nullptr, true, "required", true, true},
  field_descriptor{4, "NegotiationReceiptClaims", "authorityEpoch", 5, "integer", nullptr, true, "required", true, false},
  field_descriptor{4, "NegotiationReceiptClaims", "sessionId", 6, "string", nullptr, true, "required", true, true},
  field_descriptor{4, "NegotiationReceiptClaims", "clientNonce", 7, "string", nullptr, true, "required", true, true},
  field_descriptor{4, "NegotiationReceiptClaims", "serverNonce", 8, "string", nullptr, true, "required", true, true},
  field_descriptor{4, "NegotiationReceiptClaims", "issuedAtUnixMs", 9, "integer", nullptr, true, "required", true, false},
  field_descriptor{4, "NegotiationReceiptClaims", "expiresAtUnixMs", 10, "integer", nullptr, true, "required", true, false},
  field_descriptor{5, "NegotiationReceipt", "algorithm", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{5, "NegotiationReceipt", "keyId", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{5, "NegotiationReceipt", "claims", 3, "reference", "NegotiationReceiptClaims", true, "required", false, true},
  field_descriptor{5, "NegotiationReceipt", "mac", 4, "string", nullptr, true, "required", false, true},
  field_descriptor{6, "IdempotencyDescriptor", "key", 1, "string", nullptr, true, "required", false, true},
  field_descriptor{6, "IdempotencyDescriptor", "algorithm", 2, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{6, "IdempotencyDescriptor", "projectionVersion", 3, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{6, "IdempotencyDescriptor", "fingerprint", 4, "string", nullptr, true, "required", false, false},
  field_descriptor{6, "IdempotencyDescriptor", "issuedAtUnixMs", 5, "integer", nullptr, true, "required", false, false},
  field_descriptor{6, "IdempotencyDescriptor", "expiresAtUnixMs", 6, "integer", nullptr, true, "required", false, false},
  field_descriptor{7, "RequestEnvelope", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{7, "RequestEnvelope", "operation", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{7, "RequestEnvelope", "correlationId", 3, "string", nullptr, true, "required", false, false},
  field_descriptor{7, "RequestEnvelope", "deadlineUnixMs", 4, "integer", nullptr, false, "optional", false, false},
  field_descriptor{7, "RequestEnvelope", "negotiationReceipt", 5, "reference", "NegotiationReceipt", true, "required", false, true},
  field_descriptor{7, "RequestEnvelope", "idempotency", 6, "reference", "IdempotencyDescriptor", false, "optional", false, true},
  field_descriptor{7, "RequestEnvelope", "body", 7, "json", nullptr, true, "required", true, false},
  field_descriptor{7, "RequestEnvelope", "extensions", 8, "map<json>", nullptr, false, "optional", true, false},
  field_descriptor{8, "SafeParameter", "name", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{8, "SafeParameter", "value", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{9, "ProblemDetails", "type", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{9, "ProblemDetails", "title", 2, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{9, "ProblemDetails", "status", 3, "enum<integer>", nullptr, true, "required", true, false},
  field_descriptor{9, "ProblemDetails", "code", 4, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{9, "ProblemDetails", "retryable", 5, "boolean", nullptr, true, "required", true, false},
  field_descriptor{9, "ProblemDetails", "correlationId", 6, "string", nullptr, true, "required", true, false},
  field_descriptor{9, "ProblemDetails", "parameters", 7, "array<reference>", "SafeParameter", false, "optional", true, false},
  field_descriptor{10, "ResponseEnvelope", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{10, "ResponseEnvelope", "correlationId", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{10, "ResponseEnvelope", "success", 3, "boolean", nullptr, true, "required", true, false},
  field_descriptor{10, "ResponseEnvelope", "body", 4, "json", nullptr, false, "optional", true, false},
  field_descriptor{10, "ResponseEnvelope", "problem", 5, "reference", "ProblemDetails", false, "optional", true, false},
  field_descriptor{10, "ResponseEnvelope", "extensions", 6, "map<json>", nullptr, false, "optional", true, false},
  field_descriptor{11, "Cursor", "token", 1, "string", nullptr, true, "required", false, true},
  field_descriptor{12, "PageEnvelope", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{12, "PageEnvelope", "correlationId", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{12, "PageEnvelope", "items", 3, "array<json>", nullptr, true, "required", true, false},
  field_descriptor{12, "PageEnvelope", "state", 4, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{12, "PageEnvelope", "nextCursor", 5, "reference", "Cursor", false, "optional", true, true},
  field_descriptor{12, "PageEnvelope", "problem", 6, "reference", "ProblemDetails", false, "optional", true, false},
  field_descriptor{13, "StreamFrame", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{13, "StreamFrame", "streamId", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{13, "StreamFrame", "sequence", 3, "integer", nullptr, true, "required", true, false},
  field_descriptor{13, "StreamFrame", "kind", 4, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{13, "StreamFrame", "payload", 5, "json", nullptr, false, "optional", true, false},
  field_descriptor{13, "StreamFrame", "problem", 6, "reference", "ProblemDetails", false, "optional", true, false},
  field_descriptor{14, "CompactTransferGrant", "scheme", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{14, "CompactTransferGrant", "representation", 2, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{14, "CompactTransferGrant", "explicitObjectCount", 3, "integer", nullptr, true, "required", true, false},
  field_descriptor{14, "CompactTransferGrant", "envelope", 4, "string", nullptr, true, "required", false, true},
  field_descriptor{14, "CompactTransferGrant", "authorizationManifestSha256", 5, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{15, "TransferProbe", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{15, "TransferProbe", "operation", 2, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{15, "TransferProbe", "grant", 3, "reference", "CompactTransferGrant", true, "required", false, true},
  field_descriptor{15, "TransferProbe", "resourceTag", 4, "string", nullptr, true, "required", true, false},
  field_descriptor{15, "TransferProbe", "startOffset", 5, "integer", nullptr, true, "required", true, false},
  field_descriptor{15, "TransferProbe", "endOffsetExclusive", 6, "integer", nullptr, false, "optional", true, false},
  field_descriptor{15, "TransferProbe", "validatorTag", 7, "string", nullptr, false, "optional", true, false},
  field_descriptor{15, "TransferProbe", "expectedSha256", 8, "string", nullptr, false, "optional", true, false},
  field_descriptor{15, "TransferProbe", "contentEncoding", 9, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{15, "TransferProbe", "followRedirects", 10, "boolean", nullptr, true, "required", true, false},
  field_descriptor{16, "TransferProbeResult", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{16, "TransferProbeResult", "status", 2, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{16, "TransferProbeResult", "acceptedStart", 3, "integer", nullptr, true, "required", true, false},
  field_descriptor{16, "TransferProbeResult", "acceptedEndExclusive", 4, "integer", nullptr, true, "required", true, false},
  field_descriptor{16, "TransferProbeResult", "totalBytes", 5, "integer", nullptr, true, "required", true, false},
  field_descriptor{16, "TransferProbeResult", "validatorTag", 6, "string", nullptr, true, "required", true, false},
  field_descriptor{16, "TransferProbeResult", "contentSha256", 7, "string", nullptr, true, "required", true, false},
  field_descriptor{16, "TransferProbeResult", "terminal", 8, "boolean", nullptr, true, "required", true, false},
  field_descriptor{16, "TransferProbeResult", "problem", 9, "reference", "ProblemDetails", false, "optional", true, false},
  field_descriptor{17, "ExtensionRegistration", "code", 1, "integer", nullptr, true, "required", true, false},
  field_descriptor{17, "ExtensionRegistration", "id", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{17, "ExtensionRegistration", "owner", 3, "string", nullptr, true, "required", true, false},
  field_descriptor{17, "ExtensionRegistration", "state", 4, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{17, "ExtensionRegistration", "requirement", 5, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{17, "ExtensionRegistration", "fallback", 6, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{17, "ExtensionRegistration", "securityImpact", 7, "string", nullptr, true, "required", true, false},
  field_descriptor{17, "ExtensionRegistration", "dataImpact", 8, "string", nullptr, true, "required", true, false},
  field_descriptor{17, "ExtensionRegistration", "affectedSchemas", 9, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{17, "ExtensionRegistration", "minimumProtocol", 10, "string", nullptr, true, "required", true, false},
  field_descriptor{18, "CompatibilityEntry", "code", 1, "integer", nullptr, true, "required", true, false},
  field_descriptor{18, "CompatibilityEntry", "state", 2, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{18, "CompatibilityEntry", "selection", 3, "reference", "NegotiationSelection", true, "required", true, false},
  field_descriptor{18, "CompatibilityEntry", "requiredCapabilities", 4, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{18, "CompatibilityEntry", "authorizationManifestSha256", 5, "string", nullptr, true, "required", true, false},
  field_descriptor{18, "CompatibilityEntry", "pathManifestSha256", 6, "string", nullptr, true, "required", true, false},
  field_descriptor{18, "CompatibilityEntry", "repositoryManifestSha256", 7, "string", nullptr, true, "required", true, false},
  field_descriptor{19, "RunnerHello", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{19, "RunnerHello", "adapterId", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{19, "RunnerHello", "contractManifestSha256", 3, "string", nullptr, true, "required", true, false},
  field_descriptor{19, "RunnerHello", "operations", 4, "array<enum<string>>", nullptr, true, "required", true, false},
  field_descriptor{20, "RunnerCase", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{20, "RunnerCase", "id", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{20, "RunnerCase", "operation", 3, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{20, "RunnerCase", "input", 4, "json", nullptr, true, "required", true, false},
  field_descriptor{20, "RunnerCase", "inputKind", 5, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{20, "RunnerCase", "configuredLimits", 7, "reference", "RunnerConfiguredLimits", false, "optional", true, false},
  field_descriptor{20, "RunnerCase", "control", 8, "reference", "RunnerExecutionControl", true, "required", true, false},
  field_descriptor{20, "RunnerCase", "serverContext", 9, "json", nullptr, false, "optional", false, true},
  field_descriptor{21, "RunnerResult", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{21, "RunnerResult", "id", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{21, "RunnerResult", "result", 3, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{21, "RunnerResult", "code", 4, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{21, "RunnerResult", "preMutation", 5, "boolean", nullptr, true, "required", true, false},
  field_descriptor{21, "RunnerResult", "mutationCount", 6, "integer", nullptr, true, "required", true, false},
  field_descriptor{21, "RunnerResult", "semanticDigest", 7, "string", nullptr, false, "optional", true, false},
  field_descriptor{21, "RunnerResult", "traceDigest", 8, "string", nullptr, true, "required", true, false},
  field_descriptor{22, "RunnerReport", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{22, "RunnerReport", "adapterId", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{22, "RunnerReport", "contractManifestSha256", 3, "string", nullptr, true, "required", true, false},
  field_descriptor{22, "RunnerReport", "results", 4, "array<reference>", "RunnerResult", true, "required", true, false},
  field_descriptor{22, "RunnerReport", "passed", 5, "integer", nullptr, true, "required", true, false},
  field_descriptor{22, "RunnerReport", "failed", 6, "integer", nullptr, true, "required", true, false},
  field_descriptor{22, "RunnerReport", "reportDigest", 7, "string", nullptr, true, "required", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxControlMessageBytes", 1, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxCanonicalInputBytes", 2, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxJsonDepth", 3, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxJsonNodes", 4, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxObjectMembers", 5, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxArrayItems", 6, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxStringUtf8Bytes", 7, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxExtensionEntries", 8, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxCapabilityItems", 9, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxErrorParameters", 10, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxPageItems", 11, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxJsonlFrameBytes", 12, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxJsonlFrames", 13, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxCursorBytes", 14, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxIdempotencyKeyBytes", 15, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxReceiptBytes", 16, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxGrantBytes", 17, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxTransferRangeBytes", 18, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxHeaderBytes", 19, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxCorrelationIdBytes", 20, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxOperationBytes", 21, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxRunnerCases", 22, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxSafeParameterBytes", 23, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxDeadlineHorizonMs", 24, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxReceiptLifetimeMs", 25, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxCursorLifetimeMs", 26, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxRegistryEntries", 27, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxJsonKeyUtf8Bytes", 28, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxJsonCollectionItems", 29, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxJsonlStreamBytes", 30, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxWorkingMemoryBytes", 31, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxOperationTimeMs", 32, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxSchemaEvaluationSteps", 33, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxContractArtifacts", 34, "integer", nullptr, false, "optional", true, false},
  field_descriptor{23, "RunnerConfiguredLimits", "maxContractBytes", 35, "integer", nullptr, false, "optional", true, false},
  field_descriptor{24, "RunnerExecutionControl", "cancellation", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{24, "RunnerExecutionControl", "clockSamplesUnixMs", 2, "array<integer>", nullptr, true, "required", true, false},
  field_descriptor{25, "RunnerPrincipal", "subjectDigest", 1, "string", nullptr, true, "required", true, false},
  field_descriptor{25, "RunnerPrincipal", "tenantDigest", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{25, "RunnerPrincipal", "authorityEpoch", 3, "integer", nullptr, true, "required", true, false},
  field_descriptor{25, "RunnerPrincipal", "sessionId", 4, "string", nullptr, true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "route", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "offer", 2, "reference", "NegotiationOffer", true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "serverSelection", 3, "reference", "NegotiationSelection", true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "principal", 4, "reference", "RunnerPrincipal", true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "verificationPrincipal", 5, "reference", "RunnerPrincipal", true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "minimumCapabilities", 6, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "transportScheme", 7, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "tlsVersion", 8, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "loopbackConformance", 9, "boolean", nullptr, true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "receiptKeyId", 10, "string", nullptr, true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "receiptKeyBase64url", 11, "string", nullptr, true, "required", false, true},
  field_descriptor{26, "NegotiationCaseInput", "serverNonce", 12, "string", nullptr, true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "issueAtUnixMs", 13, "integer", nullptr, true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "verifyAtUnixMs", 14, "integer", nullptr, true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "receiptMacXor", 15, "integer", nullptr, true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "receiptLifetimeMs", 16, "integer", nullptr, true, "required", true, false},
  field_descriptor{26, "NegotiationCaseInput", "verificationSelection", 17, "reference", "NegotiationSelection", true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "route", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "targetSchema", 2, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "encoding", 3, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "document", 4, "json", nullptr, false, "optional", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "rawInput", 5, "string", nullptr, false, "optional", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "atUnixMs", 6, "integer", nullptr, true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "transportScheme", 7, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "tlsVersion", 8, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "method", 9, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "contentEncoding", 10, "string", nullptr, true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "redirectStatus", 11, "integer", nullptr, false, "optional", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "originChanged", 12, "boolean", nullptr, true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "httpStatus", 13, "integer", nullptr, false, "optional", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "authorizationDecision", 14, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "forwardedSubjectMatches", 15, "boolean", nullptr, true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "forwardedTenantMatches", 16, "boolean", nullptr, true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "allowSameOriginRedirect", 17, "boolean", nullptr, true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "headers", 18, "array<reference>", "TransportHeaderInput", true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "selectedExtensions", 19, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{27, "EnvelopeCaseInput", "rawInputUtf16CodeUnits", 20, "array<integer>", nullptr, false, "optional", true, false},
  field_descriptor{28, "FingerprintCaseInput", "route", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{28, "FingerprintCaseInput", "projections", 2, "array<json>", nullptr, true, "required", true, false},
  field_descriptor{28, "FingerprintCaseInput", "rawInputs", 3, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{28, "FingerprintCaseInput", "algorithm", 4, "string", nullptr, true, "required", true, false},
  field_descriptor{28, "FingerprintCaseInput", "idempotencyKey", 5, "string", nullptr, true, "required", true, false},
  field_descriptor{28, "FingerprintCaseInput", "retryableMutation", 6, "boolean", nullptr, true, "required", true, false},
  field_descriptor{28, "FingerprintCaseInput", "attemptProjectionIndexes", 7, "array<integer>", nullptr, true, "required", true, false},
  field_descriptor{28, "FingerprintCaseInput", "attemptSchedule", 8, "array<enum<string>>", nullptr, true, "required", true, false},
  field_descriptor{28, "FingerprintCaseInput", "idempotencyIssuedAtUnixMs", 9, "integer", nullptr, true, "required", true, false},
  field_descriptor{28, "FingerprintCaseInput", "idempotencyExpiresAtUnixMs", 10, "integer", nullptr, true, "required", true, false},
  field_descriptor{28, "FingerprintCaseInput", "atUnixMs", 11, "integer", nullptr, true, "required", true, false},
  field_descriptor{28, "FingerprintCaseInput", "tombstoneRetentionMs", 12, "integer", nullptr, true, "required", true, false},
  field_descriptor{28, "FingerprintCaseInput", "attemptAuthorizationDecisions", 13, "array<enum<string>>", nullptr, true, "required", true, false},
  field_descriptor{29, "CursorCaseInput", "route", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{29, "CursorCaseInput", "page", 2, "json", nullptr, true, "required", true, false},
  field_descriptor{29, "CursorCaseInput", "issueScope", 3, "json", nullptr, true, "required", false, true},
  field_descriptor{29, "CursorCaseInput", "readScope", 4, "json", nullptr, true, "required", false, true},
  field_descriptor{29, "CursorCaseInput", "issuedAtUnixMs", 5, "integer", nullptr, true, "required", true, false},
  field_descriptor{29, "CursorCaseInput", "readAtUnixMs", 6, "integer", nullptr, true, "required", true, false},
  field_descriptor{29, "CursorCaseInput", "ttlMs", 7, "integer", nullptr, true, "required", true, false},
  field_descriptor{29, "CursorCaseInput", "generation", 8, "integer", nullptr, true, "required", true, false},
  field_descriptor{29, "CursorCaseInput", "minimumRetainedGeneration", 9, "integer", nullptr, true, "required", true, false},
  field_descriptor{29, "CursorCaseInput", "tokenMutation", 10, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{29, "CursorCaseInput", "suppliedToken", 11, "string", nullptr, true, "required", true, false},
  field_descriptor{29, "CursorCaseInput", "tokenSource", 12, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{29, "CursorCaseInput", "lifecycleActions", 13, "array<enum<string>>", nullptr, true, "required", true, false},
  field_descriptor{29, "CursorCaseInput", "tombstoneRetentionMs", 14, "integer", nullptr, true, "required", true, false},
  field_descriptor{30, "StreamCaseInput", "route", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{30, "StreamCaseInput", "encoding", 2, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{30, "StreamCaseInput", "frames", 3, "array<json>", nullptr, true, "required", true, false},
  field_descriptor{30, "StreamCaseInput", "jsonl", 4, "string", nullptr, true, "required", true, false},
  field_descriptor{30, "StreamCaseInput", "sourceCloses", 5, "boolean", nullptr, true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "route", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "probe", 2, "json", nullptr, true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "transportResponse", 3, "json", nullptr, true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "grantLocation", 4, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "responseStatus", 6, "integer", nullptr, true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "originChanged", 7, "boolean", nullptr, true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "digestMatches", 8, "boolean", nullptr, true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "logGrant", 9, "boolean", nullptr, true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "proxyMode", 14, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "proxyConfigured", 15, "boolean", nullptr, true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "connectResult", 16, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "certificateValid", 17, "boolean", nullptr, true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "hostnameMatches", 18, "boolean", nullptr, true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "probeResult", 19, "json", nullptr, false, "optional", true, false},
  field_descriptor{31, "TransferCaseInput", "requestHeaders", 20, "array<reference>", "TransportHeaderInput", true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "responseHeaders", 21, "array<reference>", "TransportHeaderInput", true, "required", true, false},
  field_descriptor{31, "TransferCaseInput", "authorizationContext", 23, "json", nullptr, true, "required", false, true},
  field_descriptor{31, "TransferCaseInput", "authorizationPublicJwk", 24, "json", nullptr, true, "required", false, false},
  field_descriptor{31, "TransferCaseInput", "responseBodyHex", 25, "string", nullptr, true, "required", true, false},
  field_descriptor{32, "ContractArtifactInput", "path", 1, "string", nullptr, true, "required", true, false},
  field_descriptor{32, "ContractArtifactInput", "bytesHex", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{33, "ContractLoadCaseInput", "route", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{33, "ContractLoadCaseInput", "artifacts", 2, "array<reference>", "ContractArtifactInput", true, "required", true, false},
  field_descriptor{33, "ContractLoadCaseInput", "registryEntries", 3, "array<json>", nullptr, true, "required", true, false},
  field_descriptor{34, "RunnerBatchEntry", "id", 1, "string", nullptr, true, "required", true, false},
  field_descriptor{34, "RunnerBatchEntry", "operation", 2, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{35, "RunnerBatchCaseInput", "cases", 1, "array<reference>", "RunnerBatchEntry", true, "required", true, false},
  field_descriptor{36, "TraceHeader", "name", 1, "string", nullptr, true, "required", true, false},
  field_descriptor{36, "TraceHeader", "value", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{37, "TraceLogEntry", "event", 1, "string", nullptr, true, "required", true, false},
  field_descriptor{37, "TraceLogEntry", "fields", 2, "map<json>", nullptr, true, "required", true, false},
  field_descriptor{38, "AdapterTrace", "responseBody", 1, "json", nullptr, true, "required", true, false},
  field_descriptor{38, "AdapterTrace", "responseHeaders", 2, "array<reference>", "TraceHeader", true, "required", true, false},
  field_descriptor{38, "AdapterTrace", "streamFrames", 3, "array<reference>", "StreamFrame", true, "required", true, false},
  field_descriptor{38, "AdapterTrace", "logEntries", 4, "array<reference>", "TraceLogEntry", true, "required", true, false},
  field_descriptor{38, "AdapterTrace", "semanticOutput", 5, "json", nullptr, true, "required", true, false},
  field_descriptor{39, "AdapterResult", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{39, "AdapterResult", "id", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{39, "AdapterResult", "result", 3, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{39, "AdapterResult", "code", 4, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{39, "AdapterResult", "preMutation", 5, "boolean", nullptr, true, "required", true, false},
  field_descriptor{39, "AdapterResult", "mutationCount", 6, "integer", nullptr, true, "required", true, false},
  field_descriptor{39, "AdapterResult", "trace", 7, "reference", "AdapterTrace", true, "required", true, false},
  field_descriptor{40, "ReleaseAssignment", "kind", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{40, "ReleaseAssignment", "scope", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{40, "ReleaseAssignment", "name", 3, "string", nullptr, true, "required", true, false},
  field_descriptor{40, "ReleaseAssignment", "code", 4, "integer", nullptr, true, "required", true, false},
  field_descriptor{40, "ReleaseAssignment", "semanticSha256", 5, "string", nullptr, true, "required", true, false},
  field_descriptor{41, "ReleasePreflightCaseInput", "proposedSelection", 1, "reference", "ReleaseSelectionProposal", true, "required", true, false},
  field_descriptor{41, "ReleasePreflightCaseInput", "requiredCapabilities", 2, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{41, "ReleasePreflightCaseInput", "authorizationManifestSha256", 3, "string", nullptr, true, "required", true, false},
  field_descriptor{41, "ReleasePreflightCaseInput", "pathManifestSha256", 4, "string", nullptr, true, "required", true, false},
  field_descriptor{41, "ReleasePreflightCaseInput", "repositoryManifestSha256", 5, "string", nullptr, true, "required", true, false},
  field_descriptor{41, "ReleasePreflightCaseInput", "priorAssignmentSnapshotSha256", 6, "string", nullptr, true, "required", true, false},
  field_descriptor{41, "ReleasePreflightCaseInput", "proposedAssignments", 7, "array<reference>", "ReleaseAssignment", true, "required", true, false},
  field_descriptor{42, "ReleaseSelectionProposal", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{42, "ReleaseSelectionProposal", "protocolVersion", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{42, "ReleaseSelectionProposal", "messageSchemaVersion", 3, "string", nullptr, true, "required", true, false},
  field_descriptor{42, "ReleaseSelectionProposal", "repositoryFormat", 4, "string", nullptr, true, "required", true, false},
  field_descriptor{42, "ReleaseSelectionProposal", "authorizationContract", 5, "string", nullptr, true, "required", true, false},
  field_descriptor{42, "ReleaseSelectionProposal", "authorizationRegistrySha256", 6, "string", nullptr, true, "required", true, false},
  field_descriptor{42, "ReleaseSelectionProposal", "pathContract", 7, "string", nullptr, true, "required", true, false},
  field_descriptor{42, "ReleaseSelectionProposal", "pathProfile", 8, "string", nullptr, true, "required", true, false},
  field_descriptor{42, "ReleaseSelectionProposal", "pathRegistrySha256", 9, "string", nullptr, true, "required", true, false},
  field_descriptor{42, "ReleaseSelectionProposal", "eventVersion", 10, "string", nullptr, true, "required", true, false},
  field_descriptor{42, "ReleaseSelectionProposal", "transferProfile", 11, "string", nullptr, true, "required", true, false},
  field_descriptor{42, "ReleaseSelectionProposal", "extensions", 12, "array<string>", nullptr, true, "required", true, false},
  field_descriptor{42, "ReleaseSelectionProposal", "protocolRegistrySetSha256", 13, "string", nullptr, true, "required", true, false},
  field_descriptor{42, "ReleaseSelectionProposal", "repositoryRegistrySha256", 14, "string", nullptr, true, "required", true, false},
  field_descriptor{43, "TransportHeaderInput", "name", 1, "string", nullptr, true, "required", true, false},
  field_descriptor{43, "TransportHeaderInput", "value", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{44, "CursorScopeInput", "subject", 1, "string", nullptr, true, "required", false, true},
  field_descriptor{44, "CursorScopeInput", "tenant", 2, "string", nullptr, true, "required", false, true},
  field_descriptor{44, "CursorScopeInput", "repository", 3, "string", nullptr, true, "required", false, true},
  field_descriptor{44, "CursorScopeInput", "operation", 4, "string", nullptr, true, "required", false, true},
  field_descriptor{44, "CursorScopeInput", "queryDigest", 5, "string", nullptr, true, "required", false, true},
  field_descriptor{45, "IdempotencyProjectionInput", "schemaVersion", 1, "string", nullptr, true, "required", true, false},
  field_descriptor{45, "IdempotencyProjectionInput", "operation", 2, "string", nullptr, true, "required", true, false},
  field_descriptor{45, "IdempotencyProjectionInput", "body", 3, "json", nullptr, true, "required", true, false},
  field_descriptor{45, "IdempotencyProjectionInput", "extensions", 4, "map<json>", nullptr, true, "required", true, false},
  field_descriptor{46, "TransferProbeNonGrantInput", "schemaVersion", 1, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{46, "TransferProbeNonGrantInput", "operation", 2, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{46, "TransferProbeNonGrantInput", "resourceTag", 3, "string", nullptr, true, "required", true, false},
  field_descriptor{46, "TransferProbeNonGrantInput", "startOffset", 4, "integer", nullptr, true, "required", true, false},
  field_descriptor{46, "TransferProbeNonGrantInput", "endOffsetExclusive", 5, "integer", nullptr, false, "optional", true, false},
  field_descriptor{46, "TransferProbeNonGrantInput", "validatorTag", 6, "string", nullptr, false, "optional", true, false},
  field_descriptor{46, "TransferProbeNonGrantInput", "expectedSha256", 7, "string", nullptr, false, "optional", true, false},
  field_descriptor{46, "TransferProbeNonGrantInput", "contentEncoding", 8, "enum<string>", nullptr, true, "required", true, false},
  field_descriptor{46, "TransferProbeNonGrantInput", "followRedirects", 9, "boolean", nullptr, true, "required", true, false},
}};

struct CapabilityAxes;
struct NegotiationOffer;
struct NegotiationSelection;
struct NegotiationReceiptClaims;
struct NegotiationReceipt;
struct IdempotencyDescriptor;
struct RequestEnvelope;
struct SafeParameter;
struct ProblemDetails;
struct ResponseEnvelope;
struct Cursor;
struct PageEnvelope;
struct StreamFrame;
struct CompactTransferGrant;
struct TransferProbe;
struct TransferProbeResult;
struct ExtensionRegistration;
struct CompatibilityEntry;
struct RunnerHello;
struct RunnerCase;
struct RunnerResult;
struct RunnerReport;
struct RunnerConfiguredLimits;
struct RunnerExecutionControl;
struct RunnerPrincipal;
struct NegotiationCaseInput;
struct EnvelopeCaseInput;
struct FingerprintCaseInput;
struct CursorCaseInput;
struct StreamCaseInput;
struct TransferCaseInput;
struct ContractArtifactInput;
struct ContractLoadCaseInput;
struct RunnerBatchEntry;
struct RunnerBatchCaseInput;
struct TraceHeader;
struct TraceLogEntry;
struct AdapterTrace;
struct AdapterResult;
struct ReleaseAssignment;
struct ReleasePreflightCaseInput;
struct ReleaseSelectionProposal;
struct TransportHeaderInput;
struct CursorScopeInput;
struct IdempotencyProjectionInput;
struct TransferProbeNonGrantInput;

struct CapabilityAxes {
  std::vector<std::string> protocolVersions;
  std::vector<std::string> schemaVersions;
  std::vector<std::string> repositoryFormats;
  std::vector<std::string> authorizationContracts;
  std::vector<std::string> pathContracts;
  std::vector<std::string> pathProfiles;
  std::vector<std::string> eventVersions;
  std::vector<std::string> transferProfiles;
  std::vector<std::string> extensions;
  std::vector<std::string> requiredCapabilities;
};

namespace assignments::capability_axes {
inline constexpr std::uint16_t message_code = 1;
inline constexpr std::uint16_t protocol_versions = 1;
inline constexpr std::uint16_t schema_versions = 2;
inline constexpr std::uint16_t repository_formats = 3;
inline constexpr std::uint16_t authorization_contracts = 4;
inline constexpr std::uint16_t path_contracts = 5;
inline constexpr std::uint16_t path_profiles = 6;
inline constexpr std::uint16_t event_versions = 7;
inline constexpr std::uint16_t transfer_profiles = 8;
inline constexpr std::uint16_t extensions = 9;
inline constexpr std::uint16_t required_capabilities = 10;
}

struct NegotiationOffer {
  std::string schemaVersion;
  std::string clientNonce;
  std::string correlationId;
  CapabilityAxes capabilities;
  std::optional<std::int64_t> deadlineUnixMs;
};

namespace assignments::negotiation_offer {
inline constexpr std::uint16_t message_code = 2;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t client_nonce = 2;
inline constexpr std::uint16_t correlation_id = 3;
inline constexpr std::uint16_t capabilities = 4;
inline constexpr std::uint16_t deadline_unix_ms = 5;
}

struct NegotiationSelection {
  std::string schemaVersion;
  std::string protocolVersion;
  std::string messageSchemaVersion;
  std::string repositoryFormat;
  std::string authorizationContract;
  std::string authorizationRegistrySha256;
  std::string pathContract;
  std::string pathProfile;
  std::string pathRegistrySha256;
  std::string eventVersion;
  std::string transferProfile;
  std::vector<std::string> extensions;
  std::string protocolRegistrySetSha256;
  std::string repositoryRegistrySha256;
};

namespace assignments::negotiation_selection {
inline constexpr std::uint16_t message_code = 3;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t protocol_version = 2;
inline constexpr std::uint16_t message_schema_version = 3;
inline constexpr std::uint16_t repository_format = 4;
inline constexpr std::uint16_t authorization_contract = 5;
inline constexpr std::uint16_t authorization_registry_sha256 = 6;
inline constexpr std::uint16_t path_contract = 7;
inline constexpr std::uint16_t path_profile = 8;
inline constexpr std::uint16_t path_registry_sha256 = 9;
inline constexpr std::uint16_t event_version = 10;
inline constexpr std::uint16_t transfer_profile = 11;
inline constexpr std::uint16_t extensions = 12;
inline constexpr std::uint16_t protocol_registry_set_sha256 = 13;
inline constexpr std::uint16_t repository_registry_sha256 = 14;
}

struct NegotiationReceiptClaims {
  std::string schemaVersion;
  NegotiationSelection selection;
  std::string subjectDigest;
  std::string tenantDigest;
  std::int64_t authorityEpoch;
  std::string sessionId;
  std::string clientNonce;
  std::string serverNonce;
  std::int64_t issuedAtUnixMs;
  std::int64_t expiresAtUnixMs;
};

namespace assignments::negotiation_receipt_claims {
inline constexpr std::uint16_t message_code = 4;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t selection = 2;
inline constexpr std::uint16_t subject_digest = 3;
inline constexpr std::uint16_t tenant_digest = 4;
inline constexpr std::uint16_t authority_epoch = 5;
inline constexpr std::uint16_t session_id = 6;
inline constexpr std::uint16_t client_nonce = 7;
inline constexpr std::uint16_t server_nonce = 8;
inline constexpr std::uint16_t issued_at_unix_ms = 9;
inline constexpr std::uint16_t expires_at_unix_ms = 10;
}

struct NegotiationReceipt {
  std::string algorithm;
  std::string keyId;
  NegotiationReceiptClaims claims;
  std::string mac;
};

namespace assignments::negotiation_receipt {
inline constexpr std::uint16_t message_code = 5;
inline constexpr std::uint16_t algorithm = 1;
inline constexpr std::uint16_t key_id = 2;
inline constexpr std::uint16_t claims = 3;
inline constexpr std::uint16_t mac = 4;
}

struct IdempotencyDescriptor {
  std::string key;
  std::string algorithm;
  std::string projectionVersion;
  std::string fingerprint;
  std::int64_t issuedAtUnixMs;
  std::int64_t expiresAtUnixMs;
};

namespace assignments::idempotency_descriptor {
inline constexpr std::uint16_t message_code = 6;
inline constexpr std::uint16_t key = 1;
inline constexpr std::uint16_t algorithm = 2;
inline constexpr std::uint16_t projection_version = 3;
inline constexpr std::uint16_t fingerprint = 4;
inline constexpr std::uint16_t issued_at_unix_ms = 5;
inline constexpr std::uint16_t expires_at_unix_ms = 6;
}

struct RequestEnvelope {
  std::string schemaVersion;
  std::string operation;
  std::string correlationId;
  std::optional<std::int64_t> deadlineUnixMs;
  NegotiationReceipt negotiationReceipt;
  std::optional<IdempotencyDescriptor> idempotency;
  JsonValue body;
  std::optional<std::map<std::string, JsonValue>> extensions;
};

namespace assignments::request_envelope {
inline constexpr std::uint16_t message_code = 7;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t operation = 2;
inline constexpr std::uint16_t correlation_id = 3;
inline constexpr std::uint16_t deadline_unix_ms = 4;
inline constexpr std::uint16_t negotiation_receipt = 5;
inline constexpr std::uint16_t idempotency = 6;
inline constexpr std::uint16_t body = 7;
inline constexpr std::uint16_t extensions = 8;
}

struct SafeParameter {
  std::string name;
  std::string value;
};

namespace assignments::safe_parameter {
inline constexpr std::uint16_t message_code = 8;
inline constexpr std::uint16_t name = 1;
inline constexpr std::uint16_t value = 2;
}

struct ProblemDetails {
  std::string type;
  std::string title;
  std::int64_t status;
  std::string code;
  bool retryable;
  std::string correlationId;
  std::optional<std::vector<SafeParameter>> parameters;
};

namespace assignments::problem_details {
inline constexpr std::uint16_t message_code = 9;
inline constexpr std::uint16_t type = 1;
inline constexpr std::uint16_t title = 2;
inline constexpr std::uint16_t status = 3;
inline constexpr std::uint16_t code = 4;
inline constexpr std::uint16_t retryable = 5;
inline constexpr std::uint16_t correlation_id = 6;
inline constexpr std::uint16_t parameters = 7;
}

struct ResponseEnvelope {
  std::string schemaVersion;
  std::string correlationId;
  bool success;
  std::optional<JsonValue> body;
  std::optional<ProblemDetails> problem;
  std::optional<std::map<std::string, JsonValue>> extensions;
};

namespace assignments::response_envelope {
inline constexpr std::uint16_t message_code = 10;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t correlation_id = 2;
inline constexpr std::uint16_t success = 3;
inline constexpr std::uint16_t body = 4;
inline constexpr std::uint16_t problem = 5;
inline constexpr std::uint16_t extensions = 6;
}

struct Cursor {
  std::string token;
};

namespace assignments::cursor {
inline constexpr std::uint16_t message_code = 11;
inline constexpr std::uint16_t token = 1;
}

struct PageEnvelope {
  std::string schemaVersion;
  std::string correlationId;
  std::vector<JsonValue> items;
  std::string state;
  std::optional<Cursor> nextCursor;
  std::optional<ProblemDetails> problem;
};

namespace assignments::page_envelope {
inline constexpr std::uint16_t message_code = 12;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t correlation_id = 2;
inline constexpr std::uint16_t items = 3;
inline constexpr std::uint16_t state = 4;
inline constexpr std::uint16_t next_cursor = 5;
inline constexpr std::uint16_t problem = 6;
}

struct StreamFrame {
  std::string schemaVersion;
  std::string streamId;
  std::int64_t sequence;
  std::string kind;
  std::optional<JsonValue> payload;
  std::optional<ProblemDetails> problem;
};

namespace assignments::stream_frame {
inline constexpr std::uint16_t message_code = 13;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t stream_id = 2;
inline constexpr std::uint16_t sequence = 3;
inline constexpr std::uint16_t kind = 4;
inline constexpr std::uint16_t payload = 5;
inline constexpr std::uint16_t problem = 6;
}

struct CompactTransferGrant {
  std::string scheme;
  std::string representation;
  std::int64_t explicitObjectCount;
  std::string envelope;
  std::string authorizationManifestSha256;
};

namespace assignments::compact_transfer_grant {
inline constexpr std::uint16_t message_code = 14;
inline constexpr std::uint16_t scheme = 1;
inline constexpr std::uint16_t representation = 2;
inline constexpr std::uint16_t explicit_object_count = 3;
inline constexpr std::uint16_t envelope = 4;
inline constexpr std::uint16_t authorization_manifest_sha256 = 5;
}

struct TransferProbe {
  std::string schemaVersion;
  std::string operation;
  CompactTransferGrant grant;
  std::string resourceTag;
  std::int64_t startOffset;
  std::optional<std::int64_t> endOffsetExclusive;
  std::optional<std::string> validatorTag;
  std::optional<std::string> expectedSha256;
  std::string contentEncoding;
  bool followRedirects;
};

namespace assignments::transfer_probe {
inline constexpr std::uint16_t message_code = 15;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t operation = 2;
inline constexpr std::uint16_t grant = 3;
inline constexpr std::uint16_t resource_tag = 4;
inline constexpr std::uint16_t start_offset = 5;
inline constexpr std::uint16_t end_offset_exclusive = 6;
inline constexpr std::uint16_t validator_tag = 7;
inline constexpr std::uint16_t expected_sha256 = 8;
inline constexpr std::uint16_t content_encoding = 9;
inline constexpr std::uint16_t follow_redirects = 10;
}

struct TransferProbeResult {
  std::string schemaVersion;
  std::string status;
  std::int64_t acceptedStart;
  std::int64_t acceptedEndExclusive;
  std::int64_t totalBytes;
  std::string validatorTag;
  std::string contentSha256;
  bool terminal;
  std::optional<ProblemDetails> problem;
};

namespace assignments::transfer_probe_result {
inline constexpr std::uint16_t message_code = 16;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t status = 2;
inline constexpr std::uint16_t accepted_start = 3;
inline constexpr std::uint16_t accepted_end_exclusive = 4;
inline constexpr std::uint16_t total_bytes = 5;
inline constexpr std::uint16_t validator_tag = 6;
inline constexpr std::uint16_t content_sha256 = 7;
inline constexpr std::uint16_t terminal = 8;
inline constexpr std::uint16_t problem = 9;
}

struct ExtensionRegistration {
  std::int64_t code;
  std::string id;
  std::string owner;
  std::string state;
  std::string requirement;
  std::string fallback;
  std::string securityImpact;
  std::string dataImpact;
  std::vector<std::string> affectedSchemas;
  std::string minimumProtocol;
};

namespace assignments::extension_registration {
inline constexpr std::uint16_t message_code = 17;
inline constexpr std::uint16_t code = 1;
inline constexpr std::uint16_t id = 2;
inline constexpr std::uint16_t owner = 3;
inline constexpr std::uint16_t state = 4;
inline constexpr std::uint16_t requirement = 5;
inline constexpr std::uint16_t fallback = 6;
inline constexpr std::uint16_t security_impact = 7;
inline constexpr std::uint16_t data_impact = 8;
inline constexpr std::uint16_t affected_schemas = 9;
inline constexpr std::uint16_t minimum_protocol = 10;
}

struct CompatibilityEntry {
  std::int64_t code;
  std::string state;
  NegotiationSelection selection;
  std::vector<std::string> requiredCapabilities;
  std::string authorizationManifestSha256;
  std::string pathManifestSha256;
  std::string repositoryManifestSha256;
};

namespace assignments::compatibility_entry {
inline constexpr std::uint16_t message_code = 18;
inline constexpr std::uint16_t code = 1;
inline constexpr std::uint16_t state = 2;
inline constexpr std::uint16_t selection = 3;
inline constexpr std::uint16_t required_capabilities = 4;
inline constexpr std::uint16_t authorization_manifest_sha256 = 5;
inline constexpr std::uint16_t path_manifest_sha256 = 6;
inline constexpr std::uint16_t repository_manifest_sha256 = 7;
}

struct RunnerHello {
  std::string schemaVersion;
  std::string adapterId;
  std::string contractManifestSha256;
  std::vector<std::string> operations;
};

namespace assignments::runner_hello {
inline constexpr std::uint16_t message_code = 19;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t adapter_id = 2;
inline constexpr std::uint16_t contract_manifest_sha256 = 3;
inline constexpr std::uint16_t operations = 4;
}

struct RunnerConfiguredLimits {
  std::optional<std::int64_t> maxControlMessageBytes;
  std::optional<std::int64_t> maxCanonicalInputBytes;
  std::optional<std::int64_t> maxJsonDepth;
  std::optional<std::int64_t> maxJsonNodes;
  std::optional<std::int64_t> maxObjectMembers;
  std::optional<std::int64_t> maxArrayItems;
  std::optional<std::int64_t> maxStringUtf8Bytes;
  std::optional<std::int64_t> maxExtensionEntries;
  std::optional<std::int64_t> maxCapabilityItems;
  std::optional<std::int64_t> maxErrorParameters;
  std::optional<std::int64_t> maxPageItems;
  std::optional<std::int64_t> maxJsonlFrameBytes;
  std::optional<std::int64_t> maxJsonlFrames;
  std::optional<std::int64_t> maxCursorBytes;
  std::optional<std::int64_t> maxIdempotencyKeyBytes;
  std::optional<std::int64_t> maxReceiptBytes;
  std::optional<std::int64_t> maxGrantBytes;
  std::optional<std::int64_t> maxTransferRangeBytes;
  std::optional<std::int64_t> maxHeaderBytes;
  std::optional<std::int64_t> maxCorrelationIdBytes;
  std::optional<std::int64_t> maxOperationBytes;
  std::optional<std::int64_t> maxRunnerCases;
  std::optional<std::int64_t> maxSafeParameterBytes;
  std::optional<std::int64_t> maxDeadlineHorizonMs;
  std::optional<std::int64_t> maxReceiptLifetimeMs;
  std::optional<std::int64_t> maxCursorLifetimeMs;
  std::optional<std::int64_t> maxRegistryEntries;
  std::optional<std::int64_t> maxJsonKeyUtf8Bytes;
  std::optional<std::int64_t> maxJsonCollectionItems;
  std::optional<std::int64_t> maxJsonlStreamBytes;
  std::optional<std::int64_t> maxWorkingMemoryBytes;
  std::optional<std::int64_t> maxOperationTimeMs;
  std::optional<std::int64_t> maxSchemaEvaluationSteps;
  std::optional<std::int64_t> maxContractArtifacts;
  std::optional<std::int64_t> maxContractBytes;
};

namespace assignments::runner_configured_limits {
inline constexpr std::uint16_t message_code = 23;
inline constexpr std::uint16_t max_control_message_bytes = 1;
inline constexpr std::uint16_t max_canonical_input_bytes = 2;
inline constexpr std::uint16_t max_json_depth = 3;
inline constexpr std::uint16_t max_json_nodes = 4;
inline constexpr std::uint16_t max_object_members = 5;
inline constexpr std::uint16_t max_array_items = 6;
inline constexpr std::uint16_t max_string_utf8_bytes = 7;
inline constexpr std::uint16_t max_extension_entries = 8;
inline constexpr std::uint16_t max_capability_items = 9;
inline constexpr std::uint16_t max_error_parameters = 10;
inline constexpr std::uint16_t max_page_items = 11;
inline constexpr std::uint16_t max_jsonl_frame_bytes = 12;
inline constexpr std::uint16_t max_jsonl_frames = 13;
inline constexpr std::uint16_t max_cursor_bytes = 14;
inline constexpr std::uint16_t max_idempotency_key_bytes = 15;
inline constexpr std::uint16_t max_receipt_bytes = 16;
inline constexpr std::uint16_t max_grant_bytes = 17;
inline constexpr std::uint16_t max_transfer_range_bytes = 18;
inline constexpr std::uint16_t max_header_bytes = 19;
inline constexpr std::uint16_t max_correlation_id_bytes = 20;
inline constexpr std::uint16_t max_operation_bytes = 21;
inline constexpr std::uint16_t max_runner_cases = 22;
inline constexpr std::uint16_t max_safe_parameter_bytes = 23;
inline constexpr std::uint16_t max_deadline_horizon_ms = 24;
inline constexpr std::uint16_t max_receipt_lifetime_ms = 25;
inline constexpr std::uint16_t max_cursor_lifetime_ms = 26;
inline constexpr std::uint16_t max_registry_entries = 27;
inline constexpr std::uint16_t max_json_key_utf8_bytes = 28;
inline constexpr std::uint16_t max_json_collection_items = 29;
inline constexpr std::uint16_t max_jsonl_stream_bytes = 30;
inline constexpr std::uint16_t max_working_memory_bytes = 31;
inline constexpr std::uint16_t max_operation_time_ms = 32;
inline constexpr std::uint16_t max_schema_evaluation_steps = 33;
inline constexpr std::uint16_t max_contract_artifacts = 34;
inline constexpr std::uint16_t max_contract_bytes = 35;
}

struct RunnerExecutionControl {
  std::string cancellation;
  std::vector<std::int64_t> clockSamplesUnixMs;
};

namespace assignments::runner_execution_control {
inline constexpr std::uint16_t message_code = 24;
inline constexpr std::uint16_t cancellation = 1;
inline constexpr std::uint16_t clock_samples_unix_ms = 2;
}

struct RunnerCase {
  std::string schemaVersion;
  std::string id;
  std::string operation;
  JsonValue input;
  std::string inputKind;
  std::optional<RunnerConfiguredLimits> configuredLimits;
  RunnerExecutionControl control;
  std::optional<JsonValue> serverContext;
};

namespace assignments::runner_case {
inline constexpr std::uint16_t message_code = 20;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t id = 2;
inline constexpr std::uint16_t operation = 3;
inline constexpr std::uint16_t input = 4;
inline constexpr std::uint16_t input_kind = 5;
inline constexpr std::uint16_t configured_limits = 7;
inline constexpr std::uint16_t control = 8;
inline constexpr std::uint16_t server_context = 9;
}

struct RunnerResult {
  std::string schemaVersion;
  std::string id;
  std::string result;
  std::string code;
  bool preMutation;
  std::int64_t mutationCount;
  std::optional<std::string> semanticDigest;
  std::string traceDigest;
};

namespace assignments::runner_result {
inline constexpr std::uint16_t message_code = 21;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t id = 2;
inline constexpr std::uint16_t result = 3;
inline constexpr std::uint16_t code = 4;
inline constexpr std::uint16_t pre_mutation = 5;
inline constexpr std::uint16_t mutation_count = 6;
inline constexpr std::uint16_t semantic_digest = 7;
inline constexpr std::uint16_t trace_digest = 8;
}

struct RunnerReport {
  std::string schemaVersion;
  std::string adapterId;
  std::string contractManifestSha256;
  std::vector<RunnerResult> results;
  std::int64_t passed;
  std::int64_t failed;
  std::string reportDigest;
};

namespace assignments::runner_report {
inline constexpr std::uint16_t message_code = 22;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t adapter_id = 2;
inline constexpr std::uint16_t contract_manifest_sha256 = 3;
inline constexpr std::uint16_t results = 4;
inline constexpr std::uint16_t passed = 5;
inline constexpr std::uint16_t failed = 6;
inline constexpr std::uint16_t report_digest = 7;
}

struct RunnerPrincipal {
  std::string subjectDigest;
  std::string tenantDigest;
  std::int64_t authorityEpoch;
  std::string sessionId;
};

namespace assignments::runner_principal {
inline constexpr std::uint16_t message_code = 25;
inline constexpr std::uint16_t subject_digest = 1;
inline constexpr std::uint16_t tenant_digest = 2;
inline constexpr std::uint16_t authority_epoch = 3;
inline constexpr std::uint16_t session_id = 4;
}

struct NegotiationCaseInput {
  std::string route;
  NegotiationOffer offer;
  NegotiationSelection serverSelection;
  RunnerPrincipal principal;
  RunnerPrincipal verificationPrincipal;
  std::vector<std::string> minimumCapabilities;
  std::string transportScheme;
  std::string tlsVersion;
  bool loopbackConformance;
  std::string receiptKeyId;
  std::string receiptKeyBase64url;
  std::string serverNonce;
  std::int64_t issueAtUnixMs;
  std::int64_t verifyAtUnixMs;
  std::int64_t receiptMacXor;
  std::int64_t receiptLifetimeMs;
  NegotiationSelection verificationSelection;
};

namespace assignments::negotiation_case_input {
inline constexpr std::uint16_t message_code = 26;
inline constexpr std::uint16_t route = 1;
inline constexpr std::uint16_t offer = 2;
inline constexpr std::uint16_t server_selection = 3;
inline constexpr std::uint16_t principal = 4;
inline constexpr std::uint16_t verification_principal = 5;
inline constexpr std::uint16_t minimum_capabilities = 6;
inline constexpr std::uint16_t transport_scheme = 7;
inline constexpr std::uint16_t tls_version = 8;
inline constexpr std::uint16_t loopback_conformance = 9;
inline constexpr std::uint16_t receipt_key_id = 10;
inline constexpr std::uint16_t receipt_key_base64url = 11;
inline constexpr std::uint16_t server_nonce = 12;
inline constexpr std::uint16_t issue_at_unix_ms = 13;
inline constexpr std::uint16_t verify_at_unix_ms = 14;
inline constexpr std::uint16_t receipt_mac_xor = 15;
inline constexpr std::uint16_t receipt_lifetime_ms = 16;
inline constexpr std::uint16_t verification_selection = 17;
}

struct TransportHeaderInput {
  std::string name;
  std::string value;
};

namespace assignments::transport_header_input {
inline constexpr std::uint16_t message_code = 43;
inline constexpr std::uint16_t name = 1;
inline constexpr std::uint16_t value = 2;
}

struct EnvelopeCaseInput {
  std::string route;
  std::string targetSchema;
  std::string encoding;
  std::optional<JsonValue> document;
  std::optional<std::string> rawInput;
  std::int64_t atUnixMs;
  std::string transportScheme;
  std::string tlsVersion;
  std::string method;
  std::string contentEncoding;
  std::optional<std::int64_t> redirectStatus;
  bool originChanged;
  std::optional<std::int64_t> httpStatus;
  std::string authorizationDecision;
  bool forwardedSubjectMatches;
  bool forwardedTenantMatches;
  bool allowSameOriginRedirect;
  std::vector<TransportHeaderInput> headers;
  std::vector<std::string> selectedExtensions;
  std::optional<std::vector<std::int64_t>> rawInputUtf16CodeUnits;
};

namespace assignments::envelope_case_input {
inline constexpr std::uint16_t message_code = 27;
inline constexpr std::uint16_t route = 1;
inline constexpr std::uint16_t target_schema = 2;
inline constexpr std::uint16_t encoding = 3;
inline constexpr std::uint16_t document = 4;
inline constexpr std::uint16_t raw_input = 5;
inline constexpr std::uint16_t at_unix_ms = 6;
inline constexpr std::uint16_t transport_scheme = 7;
inline constexpr std::uint16_t tls_version = 8;
inline constexpr std::uint16_t method = 9;
inline constexpr std::uint16_t content_encoding = 10;
inline constexpr std::uint16_t redirect_status = 11;
inline constexpr std::uint16_t origin_changed = 12;
inline constexpr std::uint16_t http_status = 13;
inline constexpr std::uint16_t authorization_decision = 14;
inline constexpr std::uint16_t forwarded_subject_matches = 15;
inline constexpr std::uint16_t forwarded_tenant_matches = 16;
inline constexpr std::uint16_t allow_same_origin_redirect = 17;
inline constexpr std::uint16_t headers = 18;
inline constexpr std::uint16_t selected_extensions = 19;
inline constexpr std::uint16_t raw_input_utf16_code_units = 20;
}

struct FingerprintCaseInput {
  std::string route;
  std::vector<JsonValue> projections;
  std::vector<std::string> rawInputs;
  std::string algorithm;
  std::string idempotencyKey;
  bool retryableMutation;
  std::vector<std::int64_t> attemptProjectionIndexes;
  std::vector<std::string> attemptSchedule;
  std::int64_t idempotencyIssuedAtUnixMs;
  std::int64_t idempotencyExpiresAtUnixMs;
  std::int64_t atUnixMs;
  std::int64_t tombstoneRetentionMs;
  std::vector<std::string> attemptAuthorizationDecisions;
};

namespace assignments::fingerprint_case_input {
inline constexpr std::uint16_t message_code = 28;
inline constexpr std::uint16_t route = 1;
inline constexpr std::uint16_t projections = 2;
inline constexpr std::uint16_t raw_inputs = 3;
inline constexpr std::uint16_t algorithm = 4;
inline constexpr std::uint16_t idempotency_key = 5;
inline constexpr std::uint16_t retryable_mutation = 6;
inline constexpr std::uint16_t attempt_projection_indexes = 7;
inline constexpr std::uint16_t attempt_schedule = 8;
inline constexpr std::uint16_t idempotency_issued_at_unix_ms = 9;
inline constexpr std::uint16_t idempotency_expires_at_unix_ms = 10;
inline constexpr std::uint16_t at_unix_ms = 11;
inline constexpr std::uint16_t tombstone_retention_ms = 12;
inline constexpr std::uint16_t attempt_authorization_decisions = 13;
}

struct CursorCaseInput {
  std::string route;
  JsonValue page;
  JsonValue issueScope;
  JsonValue readScope;
  std::int64_t issuedAtUnixMs;
  std::int64_t readAtUnixMs;
  std::int64_t ttlMs;
  std::int64_t generation;
  std::int64_t minimumRetainedGeneration;
  std::string tokenMutation;
  std::string suppliedToken;
  std::string tokenSource;
  std::vector<std::string> lifecycleActions;
  std::int64_t tombstoneRetentionMs;
};

namespace assignments::cursor_case_input {
inline constexpr std::uint16_t message_code = 29;
inline constexpr std::uint16_t route = 1;
inline constexpr std::uint16_t page = 2;
inline constexpr std::uint16_t issue_scope = 3;
inline constexpr std::uint16_t read_scope = 4;
inline constexpr std::uint16_t issued_at_unix_ms = 5;
inline constexpr std::uint16_t read_at_unix_ms = 6;
inline constexpr std::uint16_t ttl_ms = 7;
inline constexpr std::uint16_t generation = 8;
inline constexpr std::uint16_t minimum_retained_generation = 9;
inline constexpr std::uint16_t token_mutation = 10;
inline constexpr std::uint16_t supplied_token = 11;
inline constexpr std::uint16_t token_source = 12;
inline constexpr std::uint16_t lifecycle_actions = 13;
inline constexpr std::uint16_t tombstone_retention_ms = 14;
}

struct StreamCaseInput {
  std::string route;
  std::string encoding;
  std::vector<JsonValue> frames;
  std::string jsonl;
  bool sourceCloses;
};

namespace assignments::stream_case_input {
inline constexpr std::uint16_t message_code = 30;
inline constexpr std::uint16_t route = 1;
inline constexpr std::uint16_t encoding = 2;
inline constexpr std::uint16_t frames = 3;
inline constexpr std::uint16_t jsonl = 4;
inline constexpr std::uint16_t source_closes = 5;
}

struct TransferCaseInput {
  std::string route;
  JsonValue probe;
  JsonValue transportResponse;
  std::string grantLocation;
  std::int64_t responseStatus;
  bool originChanged;
  bool digestMatches;
  bool logGrant;
  std::string proxyMode;
  bool proxyConfigured;
  std::string connectResult;
  bool certificateValid;
  bool hostnameMatches;
  std::optional<JsonValue> probeResult;
  std::vector<TransportHeaderInput> requestHeaders;
  std::vector<TransportHeaderInput> responseHeaders;
  JsonValue authorizationContext;
  JsonValue authorizationPublicJwk;
  std::string responseBodyHex;
};

namespace assignments::transfer_case_input {
inline constexpr std::uint16_t message_code = 31;
inline constexpr std::uint16_t route = 1;
inline constexpr std::uint16_t probe = 2;
inline constexpr std::uint16_t transport_response = 3;
inline constexpr std::uint16_t grant_location = 4;
inline constexpr std::uint16_t response_status = 6;
inline constexpr std::uint16_t origin_changed = 7;
inline constexpr std::uint16_t digest_matches = 8;
inline constexpr std::uint16_t log_grant = 9;
inline constexpr std::uint16_t proxy_mode = 14;
inline constexpr std::uint16_t proxy_configured = 15;
inline constexpr std::uint16_t connect_result = 16;
inline constexpr std::uint16_t certificate_valid = 17;
inline constexpr std::uint16_t hostname_matches = 18;
inline constexpr std::uint16_t probe_result = 19;
inline constexpr std::uint16_t request_headers = 20;
inline constexpr std::uint16_t response_headers = 21;
inline constexpr std::uint16_t authorization_context = 23;
inline constexpr std::uint16_t authorization_public_jwk = 24;
inline constexpr std::uint16_t response_body_hex = 25;
}

struct ContractArtifactInput {
  std::string path;
  std::string bytesHex;
};

namespace assignments::contract_artifact_input {
inline constexpr std::uint16_t message_code = 32;
inline constexpr std::uint16_t path = 1;
inline constexpr std::uint16_t bytes_hex = 2;
}

struct ContractLoadCaseInput {
  std::string route;
  std::vector<ContractArtifactInput> artifacts;
  std::vector<JsonValue> registryEntries;
};

namespace assignments::contract_load_case_input {
inline constexpr std::uint16_t message_code = 33;
inline constexpr std::uint16_t route = 1;
inline constexpr std::uint16_t artifacts = 2;
inline constexpr std::uint16_t registry_entries = 3;
}

struct RunnerBatchEntry {
  std::string id;
  std::string operation;
};

namespace assignments::runner_batch_entry {
inline constexpr std::uint16_t message_code = 34;
inline constexpr std::uint16_t id = 1;
inline constexpr std::uint16_t operation = 2;
}

struct RunnerBatchCaseInput {
  std::vector<RunnerBatchEntry> cases;
};

namespace assignments::runner_batch_case_input {
inline constexpr std::uint16_t message_code = 35;
inline constexpr std::uint16_t cases = 1;
}

struct TraceHeader {
  std::string name;
  std::string value;
};

namespace assignments::trace_header {
inline constexpr std::uint16_t message_code = 36;
inline constexpr std::uint16_t name = 1;
inline constexpr std::uint16_t value = 2;
}

struct TraceLogEntry {
  std::string event;
  std::map<std::string, JsonValue> fields;
};

namespace assignments::trace_log_entry {
inline constexpr std::uint16_t message_code = 37;
inline constexpr std::uint16_t event = 1;
inline constexpr std::uint16_t fields = 2;
}

struct AdapterTrace {
  JsonValue responseBody;
  std::vector<TraceHeader> responseHeaders;
  std::vector<StreamFrame> streamFrames;
  std::vector<TraceLogEntry> logEntries;
  JsonValue semanticOutput;
};

namespace assignments::adapter_trace {
inline constexpr std::uint16_t message_code = 38;
inline constexpr std::uint16_t response_body = 1;
inline constexpr std::uint16_t response_headers = 2;
inline constexpr std::uint16_t stream_frames = 3;
inline constexpr std::uint16_t log_entries = 4;
inline constexpr std::uint16_t semantic_output = 5;
}

struct AdapterResult {
  std::string schemaVersion;
  std::string id;
  std::string result;
  std::string code;
  bool preMutation;
  std::int64_t mutationCount;
  AdapterTrace trace;
};

namespace assignments::adapter_result {
inline constexpr std::uint16_t message_code = 39;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t id = 2;
inline constexpr std::uint16_t result = 3;
inline constexpr std::uint16_t code = 4;
inline constexpr std::uint16_t pre_mutation = 5;
inline constexpr std::uint16_t mutation_count = 6;
inline constexpr std::uint16_t trace = 7;
}

struct ReleaseAssignment {
  std::string kind;
  std::string scope;
  std::string name;
  std::int64_t code;
  std::string semanticSha256;
};

namespace assignments::release_assignment {
inline constexpr std::uint16_t message_code = 40;
inline constexpr std::uint16_t kind = 1;
inline constexpr std::uint16_t scope = 2;
inline constexpr std::uint16_t name = 3;
inline constexpr std::uint16_t code = 4;
inline constexpr std::uint16_t semantic_sha256 = 5;
}

struct ReleaseSelectionProposal {
  std::string schemaVersion;
  std::string protocolVersion;
  std::string messageSchemaVersion;
  std::string repositoryFormat;
  std::string authorizationContract;
  std::string authorizationRegistrySha256;
  std::string pathContract;
  std::string pathProfile;
  std::string pathRegistrySha256;
  std::string eventVersion;
  std::string transferProfile;
  std::vector<std::string> extensions;
  std::string protocolRegistrySetSha256;
  std::string repositoryRegistrySha256;
};

namespace assignments::release_selection_proposal {
inline constexpr std::uint16_t message_code = 42;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t protocol_version = 2;
inline constexpr std::uint16_t message_schema_version = 3;
inline constexpr std::uint16_t repository_format = 4;
inline constexpr std::uint16_t authorization_contract = 5;
inline constexpr std::uint16_t authorization_registry_sha256 = 6;
inline constexpr std::uint16_t path_contract = 7;
inline constexpr std::uint16_t path_profile = 8;
inline constexpr std::uint16_t path_registry_sha256 = 9;
inline constexpr std::uint16_t event_version = 10;
inline constexpr std::uint16_t transfer_profile = 11;
inline constexpr std::uint16_t extensions = 12;
inline constexpr std::uint16_t protocol_registry_set_sha256 = 13;
inline constexpr std::uint16_t repository_registry_sha256 = 14;
}

struct ReleasePreflightCaseInput {
  ReleaseSelectionProposal proposedSelection;
  std::vector<std::string> requiredCapabilities;
  std::string authorizationManifestSha256;
  std::string pathManifestSha256;
  std::string repositoryManifestSha256;
  std::string priorAssignmentSnapshotSha256;
  std::vector<ReleaseAssignment> proposedAssignments;
};

namespace assignments::release_preflight_case_input {
inline constexpr std::uint16_t message_code = 41;
inline constexpr std::uint16_t proposed_selection = 1;
inline constexpr std::uint16_t required_capabilities = 2;
inline constexpr std::uint16_t authorization_manifest_sha256 = 3;
inline constexpr std::uint16_t path_manifest_sha256 = 4;
inline constexpr std::uint16_t repository_manifest_sha256 = 5;
inline constexpr std::uint16_t prior_assignment_snapshot_sha256 = 6;
inline constexpr std::uint16_t proposed_assignments = 7;
}

struct CursorScopeInput {
  std::string subject;
  std::string tenant;
  std::string repository;
  std::string operation;
  std::string queryDigest;
};

namespace assignments::cursor_scope_input {
inline constexpr std::uint16_t message_code = 44;
inline constexpr std::uint16_t subject = 1;
inline constexpr std::uint16_t tenant = 2;
inline constexpr std::uint16_t repository = 3;
inline constexpr std::uint16_t operation = 4;
inline constexpr std::uint16_t query_digest = 5;
}

struct IdempotencyProjectionInput {
  std::string schemaVersion;
  std::string operation;
  JsonValue body;
  std::map<std::string, JsonValue> extensions;
};

namespace assignments::idempotency_projection_input {
inline constexpr std::uint16_t message_code = 45;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t operation = 2;
inline constexpr std::uint16_t body = 3;
inline constexpr std::uint16_t extensions = 4;
}

struct TransferProbeNonGrantInput {
  std::string schemaVersion;
  std::string operation;
  std::string resourceTag;
  std::int64_t startOffset;
  std::optional<std::int64_t> endOffsetExclusive;
  std::optional<std::string> validatorTag;
  std::optional<std::string> expectedSha256;
  std::string contentEncoding;
  bool followRedirects;
};

namespace assignments::transfer_probe_non_grant_input {
inline constexpr std::uint16_t message_code = 46;
inline constexpr std::uint16_t schema_version = 1;
inline constexpr std::uint16_t operation = 2;
inline constexpr std::uint16_t resource_tag = 3;
inline constexpr std::uint16_t start_offset = 4;
inline constexpr std::uint16_t end_offset_exclusive = 5;
inline constexpr std::uint16_t validator_tag = 6;
inline constexpr std::uint16_t expected_sha256 = 7;
inline constexpr std::uint16_t content_encoding = 8;
inline constexpr std::uint16_t follow_redirects = 9;
}

namespace limits {
inline constexpr std::uint64_t max_control_message_bytes = 1048576ULL;
inline constexpr std::uint64_t max_canonical_input_bytes = 1048576ULL;
inline constexpr std::uint64_t max_json_depth = 64ULL;
inline constexpr std::uint64_t max_json_nodes = 100000ULL;
inline constexpr std::uint64_t max_object_members = 256ULL;
inline constexpr std::uint64_t max_array_items = 4096ULL;
inline constexpr std::uint64_t max_string_utf8_bytes = 65536ULL;
inline constexpr std::uint64_t max_extension_entries = 32ULL;
inline constexpr std::uint64_t max_capability_items = 128ULL;
inline constexpr std::uint64_t max_error_parameters = 16ULL;
inline constexpr std::uint64_t max_page_items = 1000ULL;
inline constexpr std::uint64_t max_jsonl_frame_bytes = 1048576ULL;
inline constexpr std::uint64_t max_jsonl_frames = 100000ULL;
inline constexpr std::uint64_t max_cursor_bytes = 1024ULL;
inline constexpr std::uint64_t max_idempotency_key_bytes = 256ULL;
inline constexpr std::uint64_t max_receipt_bytes = 16384ULL;
inline constexpr std::uint64_t max_grant_bytes = 16384ULL;
inline constexpr std::uint64_t max_transfer_range_bytes = 1073741824ULL;
inline constexpr std::uint64_t max_header_bytes = 32768ULL;
inline constexpr std::uint64_t max_correlation_id_bytes = 128ULL;
inline constexpr std::uint64_t max_operation_bytes = 256ULL;
inline constexpr std::uint64_t max_runner_cases = 1024ULL;
inline constexpr std::uint64_t max_safe_parameter_bytes = 1024ULL;
inline constexpr std::uint64_t max_deadline_horizon_ms = 86400000ULL;
inline constexpr std::uint64_t max_receipt_lifetime_ms = 300000ULL;
inline constexpr std::uint64_t max_cursor_lifetime_ms = 86400000ULL;
inline constexpr std::uint64_t max_registry_entries = 4096ULL;
inline constexpr std::uint64_t max_json_key_utf8_bytes = 256ULL;
inline constexpr std::uint64_t max_json_collection_items = 100000ULL;
inline constexpr std::uint64_t max_jsonl_stream_bytes = 67108864ULL;
inline constexpr std::uint64_t max_working_memory_bytes = 67108864ULL;
inline constexpr std::uint64_t max_operation_time_ms = 120000ULL;
inline constexpr std::uint64_t max_schema_evaluation_steps = 1000000ULL;
inline constexpr std::uint64_t max_contract_artifacts = 4096ULL;
inline constexpr std::uint64_t max_contract_bytes = 67108864ULL;
}

namespace error_codes {
inline constexpr std::uint16_t protocol_malformed = 1;
inline constexpr std::uint16_t protocol_limit_exceeded = 2;
inline constexpr std::uint16_t protocol_unsupported = 3;
inline constexpr std::uint16_t negotiation_no_common_version = 4;
inline constexpr std::uint16_t negotiation_required_capability_unknown = 5;
inline constexpr std::uint16_t negotiation_downgrade_rejected = 6;
inline constexpr std::uint16_t negotiation_receipt_invalid = 7;
inline constexpr std::uint16_t negotiation_receipt_expired = 8;
inline constexpr std::uint16_t authorization_denied = 9;
inline constexpr std::uint16_t idempotency_key_required = 10;
inline constexpr std::uint16_t idempotency_key_reuse = 11;
inline constexpr std::uint16_t cursor_invalid = 12;
inline constexpr std::uint16_t cursor_scope_mismatch = 13;
inline constexpr std::uint16_t cursor_expired = 14;
inline constexpr std::uint16_t cursor_gap = 15;
inline constexpr std::uint16_t stream_incomplete = 16;
inline constexpr std::uint16_t stream_sequence_invalid = 17;
inline constexpr std::uint16_t transfer_range_invalid = 18;
inline constexpr std::uint16_t transfer_validator_mismatch = 19;
inline constexpr std::uint16_t transfer_grant_invalid = 20;
inline constexpr std::uint16_t redirect_forbidden = 21;
inline constexpr std::uint16_t compression_forbidden = 22;
inline constexpr std::uint16_t deadline_exceeded = 23;
inline constexpr std::uint16_t cancelled = 24;
inline constexpr std::uint16_t internal_error = 25;
}

} // namespace opengamevcs::protocol::v1
