export const CONTRACT_VERSION = '0.2.0';
export const PACKAGE_NAME = '@opengamevcs/identity-policy-audit-contract-v1';
export const SCHEMA_DIALECT = 'https://json-schema.org/draft/2020-12/schema';

const ID = '^[a-z][a-z0-9.-]{0,127}$';
const OPAQUE = '^[A-Za-z0-9._:-]{1,256}$';
const SHA256 = '^[0-9a-f]{64}$';
const PATH_PROFILE = '^[a-z][a-z0-9]*(?:-[a-z0-9]+)*(?:\\.[a-z][a-z0-9]*(?:-[a-z0-9]+)*)+/[a-z][a-z0-9]*(?:-[a-z0-9]+)*@[1-9][0-9]{0,9}$';
const AUTHORIZATION_REQUEST = 'https://schemas.opengamevcs.org/authorization/v1/AuthorizationRequest.schema.json';
const AUDIT_EVENT = 'https://schemas.opengamevcs.org/authorization/v1/AuditEvent.schema.json';

const text = (maximum = 256, minimum = 1, pattern) => ({
  type: 'string', minLength: minimum, maxLength: maximum, ...(pattern ? { pattern } : {}),
});
const uint = (minimum = 0, maximum = Number.MAX_SAFE_INTEGER) => ({ type: 'integer', minimum, maximum });
const array = (items, maxItems, minItems = 0) => ({ type: 'array', items, minItems, maxItems });
const closed = (properties, required = Object.keys(properties)) => ({
  type: 'object', additionalProperties: false, properties, required,
});

export const LIMITS = Object.freeze({
  maxPolicyRules: 1_024,
  maxRuleSubjects: 128,
  maxRulePathPrefixes: 128,
  maxAuthorizedViewCandidates: 10_000,
  maxAuthorizedViewItems: 1_000,
  maxCredentials: 100_000,
  maxAuditRecordBytes: 16_384,
  maxAuditQueryRecords: 10_000,
  maxRateBuckets: 100_000,
  maxTokenBytes: 1_024,
  maxAuthenticationTransactions: 100_000,
  maxOidcResponseBytes: 262_144,
  maxOidcGroups: 128,
  maxPolicyPreviewRequests: 1_000,
  maxBatchAuthorizationResources: 1_000,
  maxDecisionCommitmentBytes: 2_048,
  maxBootstrapFailedAttempts: 10,
  authorizationCodeTtlSeconds: 600,
  deviceCodeTtlSeconds: 900,
  oidcClockSkewSeconds: 60,
  oidcNetworkTimeoutMilliseconds: 10_000,
  revocationMaximumLagSeconds: 5,
  sessionMaxTtlSeconds: 28_800,
  serviceTokenMaxTtlSeconds: 3_600,
  transferGrantMaxTtlSeconds: 300,
});

const subjectScope = closed({
  identities: array(text(128, 1, ID), LIMITS.maxRuleSubjects),
  groups: array(text(128, 1, ID), LIMITS.maxRuleSubjects),
  actorClasses: array(text(128, 1, ID), 32),
});

const rule = closed({
  id: text(128, 1, ID),
  effect: { enum: ['allow', 'deny'] },
  subjects: subjectScope,
  tenant: text(128, 1, ID),
  repository: text(128, 1, ID),
  references: array(text(128, 1, ID), 128),
  pathPrefixes: array(text(4_096, 0), LIMITS.maxRulePathPrefixes),
  resourceTypes: array(text(128, 1, ID), 64, 1),
  permissions: array(text(128, 1, '^[a-z][a-z0-9.-]{0,127}$'), 64, 1),
});

const credentialScope = closed({
  tenants: array(text(128, 1, ID), 16, 1),
  repositories: array(text(128, 1, ID), 128, 1),
  references: array(text(128, 1, ID), 128),
  pathPrefixes: array(text(4_096, 0), LIMITS.maxRulePathPrefixes),
  permissions: array(text(128, 1, '^[a-z][a-z0-9.-]{0,127}$'), 64, 1),
});

export const SCHEMAS = {
  'PolicyDocument.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/PolicyDocument.schema.json',
    title: 'IdentityPolicyDocumentV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/policy/v1' },
      id: text(128, 1, ID),
      version: text(64, 1, ID),
      generation: uint(1),
      authorityEpoch: uint(1),
      pathProfile: text(328, 1, PATH_PROFILE),
      caseMode: { enum: ['case-sensitive', 'case-folded'] },
      default: { const: 'deny' },
      composition: { const: 'deny-overrides-v1' },
      rules: array(rule, LIMITS.maxPolicyRules, 1),
    }),
    'x-ogvcs-imported-assignments': {
      permissions: 'ogvcs.authorization@1/permissions',
      resourceTypes: 'ogvcs.authorization@1/resources',
      actorClasses: 'ogvcs.authorization@1/actor-classes',
      paths: 'ogvcs.path-filesystem@1',
    },
    'x-ogvcs-license': 'MIT',
  },
  'CredentialRecord.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/CredentialRecord.schema.json',
    title: 'IdentityCredentialRecordV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/credential-record/v1' },
      id: text(128, 1, ID),
      subject: text(128, 1, ID),
      actorClass: text(128, 1, ID),
      credentialClass: { enum: ['session', 'service-token'] },
      generation: uint(1),
      authorityEpoch: uint(1),
      issuedAt: uint(),
      expiresAt: uint(1),
      state: { enum: ['active', 'revoked'] },
      groups: array(text(128, 1, ID), 64),
      scope: credentialScope,
      secretDigest: text(64, 64, SHA256),
    }),
    'x-ogvcs-secret-field-policy': 'digest-only; plaintext is returned once and never persisted',
    'x-ogvcs-license': 'MIT',
  },
  'AuthorityState.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/AuthorityState.schema.json',
    title: 'IdentityAuthorityStateV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/authority-state/v1' },
      authorityEpoch: uint(1),
      keyGeneration: uint(1),
    }),
    'x-ogvcs-license': 'MIT',
  },
  'AuditChainRecord.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/AuditChainRecord.schema.json',
    title: 'IdentityAuditChainRecordV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/audit-chain-record/v1' },
      tenant: text(128, 1, ID),
      sequence: uint(1),
      previousHash: { oneOf: [{ type: 'null' }, text(64, 64, SHA256)] },
      eventHash: text(64, 64, SHA256),
      recordHash: text(64, 64, SHA256),
      event: { $ref: AUDIT_EVENT },
    }),
    'x-ogvcs-chain-domain': 'OGVCS-IDENTITY-AUDIT-CHAIN-V1',
    'x-ogvcs-license': 'MIT',
  },
  'AuditCheckpoint.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/AuditCheckpoint.schema.json',
    title: 'IdentityAuditCheckpointV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/audit-checkpoint/v1' },
      tenant: text(128, 1, ID),
      records: uint(),
      tailHash: { oneOf: [{ type: 'null' }, text(64, 64, SHA256)] },
    }),
    'x-ogvcs-trust-boundary': 'retain outside the mutable audit-record store',
    'x-ogvcs-license': 'MIT',
  },
  'AuthorizationInvocation.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/AuthorizationInvocation.schema.json',
    title: 'IdentityAuthorizationInvocationV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/authorization-invocation/v1' },
      credentialToken: text(LIMITS.maxTokenBytes),
      request: { $ref: AUTHORIZATION_REQUEST },
    }),
    'x-ogvcs-license': 'MIT',
  },
  'AuthorizedAuditEvent.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/AuthorizedAuditEvent.schema.json',
    title: 'IdentityAuthorizedAuditEventV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/authorized-audit-event/v1' },
      eventClass: text(128, 1, ID),
      occurredAt: uint(),
      repository: text(128, 1, ID),
      permission: text(128, 1, '^[a-z][a-z0-9.-]{0,127}$'),
      outcomeCode: text(128, 1, '^[A-Z][A-Z0-9_]{0,127}$'),
      disclosure: {
        type: 'object', additionalProperties: false,
        properties: {
          actorPseudonym: text(42, 42, '^pseudonym:[0-9a-f]{32}$'),
          targetClass: text(128, 1, ID),
          changeRef: text(256, 1, OPAQUE),
        },
      },
    }),
    'x-ogvcs-imported-assignments': {
      eventClasses: 'ogvcs.authorization@1/audit-classes',
      permissions: 'ogvcs.authorization@1/permissions',
      outcomeCodes: 'ogvcs.authorization@1/decisions',
    },
    'x-ogvcs-privacy': 'contains no tenant-global chain position, hashes, hidden counts, or gap markers',
    'x-ogvcs-license': 'MIT',
  },
  'AuthorizedAuditView.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/AuthorizedAuditView.schema.json',
    title: 'IdentityAuthorizedAuditViewV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/authorized-audit-view/v1' },
      items: array({ $ref: 'AuthorizedAuditEvent.schema.json' }, LIMITS.maxAuditQueryRecords),
    }),
    'x-ogvcs-requires': 'complete chain verification against an externally retained checkpoint before projection',
    'x-ogvcs-license': 'MIT',
  },
  'OidcProvider.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/OidcProvider.schema.json',
    title: 'IdentityOidcProviderV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/oidc-provider/v1' },
      id: text(128, 1, ID),
      issuer: text(2_048, 1, '^https://[^\\u0000-\\u0020]+$'),
      authorizationEndpoint: text(2_048, 1, '^https://[^\\u0000-\\u0020]+$'),
      tokenEndpoint: text(2_048, 1, '^https://[^\\u0000-\\u0020]+$'),
      deviceAuthorizationEndpoint: { oneOf: [{ type: 'null' }, text(2_048, 1, '^https://[^\\u0000-\\u0020]+$')] },
      jwksUri: text(2_048, 1, '^https://[^\\u0000-\\u0020]+$'),
      clientId: text(256, 1, OPAQUE),
      redirectUri: text(2_048, 1, '^https://[^\\u0000-\\u0020]+$'),
      scopes: array(text(128, 1, '^[A-Za-z0-9._:-]+$'), 32, 1),
      signingAlgorithms: array({ enum: ['RS256', 'ES256'] }, 2, 1),
      subjectClaim: { const: 'sub' },
      groupClaim: { oneOf: [{ type: 'null' }, text(128, 1, ID)] },
    }),
    'x-ogvcs-network-boundary': 'exact HTTPS endpoints, no redirect following, bounded responses, injected deadline',
    'x-ogvcs-license': 'MIT',
  },
  'AuthenticationTransaction.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/AuthenticationTransaction.schema.json',
    title: 'IdentityAuthenticationTransactionV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/authentication-transaction/v1' },
      id: text(128, 1, ID),
      providerId: text(128, 1, ID),
      flow: { enum: ['authorization-code-pkce', 'device-code'] },
      stateDigest: text(64, 64, SHA256),
      nonceDigest: text(64, 64, SHA256),
      verifierDigest: { oneOf: [{ type: 'null' }, text(64, 64, SHA256)] },
      deviceCodeDigest: { oneOf: [{ type: 'null' }, text(64, 64, SHA256)] },
      createdAt: uint(),
      expiresAt: uint(1),
      nextPollAt: { oneOf: [{ type: 'null' }, uint()] },
      state: { enum: ['pending', 'claimed', 'complete', 'failed'] },
    }),
    'x-ogvcs-secret-field-policy': 'the public record contains only domain-separated digests; an atomic private transaction compartment retains bounded verifier, state, nonce, or device-code material until one-use completion',
    'x-ogvcs-license': 'MIT',
  },
  'BootstrapState.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/BootstrapState.schema.json',
    title: 'IdentityBootstrapStateV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/bootstrap-state/v1' },
      generation: uint(1),
      administratorSubject: text(128, 1, ID),
      recoveryDigest: text(64, 64, SHA256),
      recoveryConfigured: { type: 'boolean' },
      externalRecoveryConfigured: { type: 'boolean' },
      localLoginEnabled: { type: 'boolean' },
      failedAttempts: uint(),
      authorityEpoch: uint(1),
    }),
    'x-ogvcs-invariant': 'local login may be disabled only after a recovery path is configured; recovery material is returned once',
    'x-ogvcs-license': 'MIT',
  },
  'PolicyMutation.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/PolicyMutation.schema.json',
    title: 'IdentityPolicyMutationV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/policy-mutation/v1' },
      mutationId: text(256, 1, OPAQUE),
      tenant: text(128, 1, ID),
      repository: text(128, 1, ID),
      expectedGeneration: uint(1),
      nextPolicy: { $ref: 'PolicyDocument.schema.json' },
      previewRequests: array({ $ref: AUTHORIZATION_REQUEST }, LIMITS.maxPolicyPreviewRequests),
      reason: text(256, 1, '^[^\\u0000-\\u001F\\u007F]+$'),
      diffRef: text(256, 1, OPAQUE),
    }),
    'x-ogvcs-atomicity': 'compare-and-swap policy generation and append policy.changed in one authority transaction',
    'x-ogvcs-license': 'MIT',
  },
  'TransactionCredentialEvidence.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/TransactionCredentialEvidence.schema.json',
    title: 'IdentityTransactionCredentialEvidenceV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/transaction-credential-evidence/v1' },
      presentationDigest: text(64, 64, SHA256),
      credentialId: text(128, 1, ID),
      credentialGeneration: uint(1),
      subjectDigest: text(64, 64, SHA256),
      tenant: text(128, 1, ID),
      authorityEpoch: uint(1),
      policyGeneration: uint(1),
      issuedAt: uint(),
      expiresAt: uint(1),
      authenticatedScopeDigest: text(64, 64, SHA256),
    }),
    'x-ogvcs-trust-boundary': 'created by the credential authority; request callers cannot select epochs, generations, or scope digests',
    'x-ogvcs-license': 'MIT',
  },
  'TransactionAuthorizedView.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/TransactionAuthorizedView.schema.json',
    title: 'IdentityTransactionAuthorizedViewV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/transaction-authorized-view/v1' },
      transactionId: text(256, 1, OPAQUE),
      evidenceDigest: text(64, 64, SHA256),
      subjectDigest: text(64, 64, SHA256),
      authenticatedScopeDigest: text(64, 64, SHA256),
      requestFingerprint: text(64, 64, SHA256),
      decisionDigest: text(64, 64, SHA256),
      tenant: text(128, 1, ID),
      repository: text(128, 1, ID),
      permission: text(128, 1, '^[a-z][a-z0-9.-]{0,127}$'),
      authorityEpoch: uint(1),
      credentialGeneration: uint(1),
      policyGeneration: uint(1),
      expiresAt: uint(1),
    }),
    'x-ogvcs-invariant': 'the same database transaction rechecks credential, epoch, policy, permission, and exact resources before mutation or response',
    'x-ogvcs-license': 'MIT',
  },
  'AuthorizedResourceBatch.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/AuthorizedResourceBatch.schema.json',
    title: 'IdentityAuthorizedResourceBatchV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/authorized-resource-batch/v1' },
      transactionId: text(256, 1, OPAQUE),
      resourceSetDigest: text(64, 64, SHA256),
      items: array(closed({ decisionDigest: text(64, 64, SHA256) }), LIMITS.maxBatchAuthorizationResources, 1),
    }),
    'x-ogvcs-invariant': 'items correspond in ascending canonical-resource byte order to one exact, same-transaction recheck; duplicate resources fail closed',
    'x-ogvcs-license': 'MIT',
  },
  'TransactionDecisionCommitment.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/TransactionDecisionCommitment.schema.json',
    title: 'IdentityTransactionDecisionCommitmentV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/transaction-decision-commitment/v1' },
      commitmentId: text(256, 1, OPAQUE),
      transactionId: text(256, 1, OPAQUE),
      correlationId: text(256, 1, OPAQUE),
      tenant: text(128, 1, ID),
      repository: text(128, 1, ID),
      authorityEpoch: uint(1),
      decisionDigest: text(64, 64, SHA256),
      resourceSetDigest: text(64, 64, SHA256),
      resultDigest: text(64, 64, SHA256),
      sequence: uint(1),
      previousHash: { oneOf: [{ type: 'null' }, text(64, 64, SHA256)] },
      recordHash: text(64, 64, SHA256),
    }),
    'x-ogvcs-separation': 'ordinary authorization decision commitment; not a substitute for a frozen privileged OGVCS-003 AuditEvent',
    'x-ogvcs-license': 'MIT',
  },
  'RevocationReceipt.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/RevocationReceipt.schema.json',
    title: 'IdentityRevocationReceiptV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/revocation-receipt/v1' },
      revocationId: text(256, 1, OPAQUE),
      tenant: text(128, 1, ID),
      credentialId: text(128, 1, ID),
      credentialGeneration: uint(1),
      authorityEpoch: uint(1),
      effectiveAt: uint(),
      maximumAuthorizingUntil: uint(),
      auditRecordHash: text(64, 64, SHA256),
    }),
    'x-ogvcs-bound': 'maximumAuthorizingUntil-effectiveAt <= revocationMaximumLagSeconds',
    'x-ogvcs-license': 'MIT',
  },
  'EpochPromotionReceipt.schema.json': {
    $schema: SCHEMA_DIALECT,
    $id: 'https://schemas.opengamevcs.dev/identity-policy-audit/v1/EpochPromotionReceipt.schema.json',
    title: 'IdentityEpochPromotionReceiptV1',
    ...closed({
      schemaVersion: { const: 'ogvcs.identity-policy/epoch-promotion-receipt/v1' },
      promotionId: text(256, 1, OPAQUE),
      tenant: text(128, 1, ID),
      previousAuthorityEpoch: uint(1),
      authorityEpoch: uint(1),
      keyGeneration: uint(1),
      effectiveAt: uint(),
      auditRecordHash: text(64, 64, SHA256),
      recoveryBoundaryDigest: text(64, 64, SHA256),
    }),
    'x-ogvcs-invariant': 'authority epoch and key generation advance atomically with the immutable authority.epoch-changed event',
    'x-ogvcs-license': 'MIT',
  },
};

export const REGISTRIES = {
  limits: {
    schemaVersion: 'ogvcs.identity-policy/registry/v1', registry: 'limits', version: 1,
    license: 'MIT', entries: Object.entries(LIMITS).map(([name, value], index) => ({ code: index + 1, name, value })),
  },
};

export const VECTORS = {
  'security-core.json': {
    schemaVersion: 'ogvcs.identity-policy/vectors/v1',
    cases: [
      ['canonical-path-allow', 'allow', ['OGVCS-009-FR-03', 'OGVCS-009-FR-04']],
      ['explicit-deny-overrides', 'DENY_NOT_AUTHORIZED', ['OGVCS-009-FR-03']],
      ['malformed-path-fails-closed', 'DENY_CONTEXT_INCOMPLETE', ['OGVCS-009-FR-04']],
      ['evaluator-failure-fails-closed', 'DENY_POLICY_UNAVAILABLE', ['OGVCS-009-FR-04']],
      ['authorized-view-hides-paths-and-counts', 'non-disclosing', ['OGVCS-009-FR-05']],
      ['session-stale-epoch', 'DENY_EPOCH_STALE', ['OGVCS-009-FR-10', 'OGVCS-009-NFR-04']],
      ['service-token-revoked', 'DENY_NOT_AUTHORIZED', ['OGVCS-009-FR-02', 'OGVCS-009-NFR-02']],
      ['transfer-grant-stale-epoch', 'DENY_EPOCH_STALE', ['OGVCS-009-FR-06', 'OGVCS-009-NFR-04']],
      ['transfer-grant-revoked', 'DENY_GRANT_INVALID', ['OGVCS-009-FR-06', 'OGVCS-009-NFR-02']],
      ['authority-promotion-audited', 'verified', ['OGVCS-009-FR-10', 'OGVCS-009-FR-11']],
      ['audit-chain-tamper', 'tamper-detected', ['OGVCS-009-FR-08', 'OGVCS-009-NFR-03']],
      ['cross-tenant-path-enumeration', 'same-safe-error', ['OGVCS-009-FR-05', 'OGVCS-009-FR-09']],
      ['rate-limit-before-lookup', 'DENY_RATE_LIMITED', ['OGVCS-009-FR-09']],
      ['policy-rule-resource-bound', 'LIMIT_EXCEEDED', ['OGVCS-009-FR-03']],
      ['authorized-view-resource-bound', 'LIMIT_EXCEEDED', ['OGVCS-009-FR-05']],
    ].map(([id, expected, requirementIds]) => ({ id, expected, requirementIds })),
  },
  'production-boundaries.json': {
    schemaVersion: 'ogvcs.identity-policy/vectors/v1',
    cases: [
      ['oidc-pkce-code-success', 'session-issued', ['OGVCS-009-FR-01', 'OGVCS-009-AC-05']],
      ['oidc-state-replay-denied', 'AUTHENTICATION_DENIED', ['OGVCS-009-FR-01', 'OGVCS-009-FR-09']],
      ['oidc-id-token-signature-invalid', 'AUTHENTICATION_DENIED', ['OGVCS-009-FR-01']],
      ['oidc-outage-no-local-fallback', 'AUTHENTICATION_DENIED', ['OGVCS-009-FR-01', 'OGVCS-009-AC-05']],
      ['device-flow-slow-down', 'pending', ['OGVCS-009-FR-01']],
      ['bootstrap-disable-requires-recovery', 'STATE_CONFLICT', ['OGVCS-009-FR-01']],
      ['policy-preview-cas-audit', 'committed', ['OGVCS-009-FR-07']],
      ['policy-change-lost-race', 'STATE_CONFLICT', ['OGVCS-009-FR-07']],
      ['transaction-credential-caller-epoch-ignored', 'EPOCH_STALE', ['OGVCS-009-FR-04', 'OGVCS-009-FR-10']],
      ['transaction-view-resource-substitution', 'AUTHENTICATION_DENIED', ['OGVCS-009-FR-04', 'OGVCS-009-FR-05']],
      ['transaction-decision-commitment-same-tx', 'committed', ['OGVCS-009-FR-04', 'OGVCS-009-FR-08']],
      ['trusted-checkpoint-request-substitution', 'INPUT_INVALID', ['OGVCS-009-FR-08']],
      ['revocation-receipt-bounded', 'revoked', ['OGVCS-009-FR-02', 'OGVCS-009-NFR-02']],
      ['rotating-invalid-token-source-rate', 'DENY_RATE_LIMITED', ['OGVCS-009-FR-09']],
    ].map(([id, expected, requirementIds]) => ({ id, expected, requirementIds })),
  },
  'authorized-resource-batch-golden.json': {
    schemaVersion: 'ogvcs.identity-policy/vectors/v1',
    cases: [
      ['canonical-sorted-resources', 'exact-canonical-bytes', ['OGVCS-009-FR-04', 'OGVCS-009-FR-05']],
    ].map(([id, expected, requirementIds]) => ({ id, expected, requirementIds })),
    inputResources: [
      { type: 'path', path: 'Game/Zeta.asset', fileId: null, objectId: null, name: null },
      { type: 'path', path: 'Game/Alpha.asset', fileId: null, objectId: null, name: null },
    ],
    canonicalResourcePaths: ['Game/Alpha.asset', 'Game/Zeta.asset'],
    batch: {
      schemaVersion: 'ogvcs.identity-policy/authorized-resource-batch/v1',
      transactionId: 'tx.golden.1',
      resourceSetDigest: 'f766b70a50ec71f7ce8ca8a3633f3ede6e7a6786f9d834738dd3e83fa085f9bf',
      items: [
        { decisionDigest: '1111111111111111111111111111111111111111111111111111111111111111' },
        { decisionDigest: '2222222222222222222222222222222222222222222222222222222222222222' },
      ],
    },
    canonicalJson: '{"items":[{"decisionDigest":"1111111111111111111111111111111111111111111111111111111111111111"},{"decisionDigest":"2222222222222222222222222222222222222222222222222222222222222222"}],"resourceSetDigest":"f766b70a50ec71f7ce8ca8a3633f3ede6e7a6786f9d834738dd3e83fa085f9bf","schemaVersion":"ogvcs.identity-policy/authorized-resource-batch/v1","transactionId":"tx.golden.1"}',
  },
};
