// Generated by scripts/generate-bindings.mjs. Do not edit.
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export type AuthorizationPermission = "discover" | "metadata.read" | "content.materialize" | "content.upload" | "lock.create" | "submit" | "review" | "export" | "policy.administer" | "lock.force-unlock" | "repair" | "retention.delete" | "audit.read" | "impersonate";
export type AuthorizationResourceType = "repository" | "reference" | "snapshot" | "tree" | "path" | "object" | "content" | "lock" | "review" | "search" | "event" | "cache-entry" | "export" | "policy" | "audit" | "retention" | "repair-job" | "sandbox-job";
export type AuthorizationDecisionCode = "ALLOW_EXPLICIT" | "ALLOW_PUBLIC" | "DENY_NOT_AUTHORIZED" | "DENY_CONTEXT_INCOMPLETE" | "DENY_POLICY_UNAVAILABLE" | "DENY_EPOCH_STALE" | "DENY_GRANT_INVALID" | "DENY_GRANT_EXPIRED" | "DENY_GRANT_REPLAY" | "DENY_AUDIENCE_MISMATCH" | "DENY_RESOURCE_SCOPE" | "DENY_PRIVILEGED_REASON_REQUIRED" | "DENY_SANDBOX_REQUIREMENTS" | "DENY_RATE_LIMITED" | "DENY_POLICY_GENERATION_MISMATCH" | "DENY_TENANT_BOUNDARY";
export type AuthorizationAuditClass = "policy.changed" | "lock.force-unlocked" | "export.requested" | "export.completed" | "retention.deleted" | "impersonation.started" | "impersonation.ended" | "repair.executed" | "audit.accessed" | "grant.revoked" | "authority.epoch-changed";
export type AuthorizationActorClass = "anonymous" | "human" | "service" | "administrator" | "cache" | "sandbox-worker";
export type AuthorizationCredentialClass = "anonymous" | "session" | "service-token" | "transfer-grant" | "offline-lock-receipt";
export type AuthorizationContractErrorCode = 'AUTHZ_INPUT_INVALID' | 'AUTHZ_CONTRACT_INVALID' | 'AUTHZ_LIMIT_EXCEEDED' | 'AUTHZ_TIMEOUT' | 'AUTHZ_ADAPTER_PROTOCOL' | 'AUTHZ_ADAPTER_FAILED' | 'AUTHZ_IO_ERROR';
export interface AuthorizationActor { id: string; class: AuthorizationActorClass; groups: string[]; credentialClass: AuthorizationCredentialClass; credentialGeneration: number; credentialStatus: 'active' | 'revoked'; authorityEpoch: number; }
export interface AuthorizationResource { type: AuthorizationResourceType; path: string | null; fileId: string | null; objectId: string | null; name: string | null; }
export interface AuthorizationRequest { schemaVersion: 'ogvcs.authorization/request/v1'; requestId: string; actor: AuthorizationActor; tenant: string; repository: string; permission: AuthorizationPermission; reason: string | null; resource: AuthorizationResource; context: { reference: string | null; snapshot: string | null; policyGeneration: number; authorityEpoch: number }; }
export interface AuthorizationPolicyRule { id: string; effect: 'allow' | 'deny'; actors: string[]; groups: string[]; actorClasses: AuthorizationActorClass[]; tenants: string[]; repositories: string[]; references: string[]; pathPrefixes: string[]; resourceTypes: AuthorizationResourceType[]; permissions: AuthorizationPermission[]; }
export interface AuthorizationPolicyFixture { schemaVersion: 'ogvcs.authorization/policy-fixture/v1'; id: string; version: string; policyGeneration: number; authorityEpoch: number; default: 'deny'; composition: 'deny-overrides-v1'; rules: AuthorizationPolicyRule[]; }
export interface AuthorizationDecision { schemaVersion: 'ogvcs.authorization/decision/v1'; requestId: string; allowed: boolean; code: AuthorizationDecisionCode; policyVersion: string; policyGeneration: number; decisionFingerprint: string; }
export interface AuthorizationAuditEvent { schemaVersion: 'ogvcs.authorization/audit-event/v1'; eventId: string; eventClass: AuthorizationAuditClass; occurredAt: number; tenant: string; repository: string; actorClass: AuthorizationActorClass; actorPseudonym: string; permission: AuthorizationPermission; reason: string; outcomeCode: AuthorizationDecisionCode; correlationId: string; details: { targetClass: string; changeRef: string | null }; }
export interface AuthorizationOutcome { result: 'allow' | 'deny'; code: AuthorizationDecisionCode; }
export interface TransferGrantClaims { schemaVersion: 'ogvcs.authorization/transfer-grant-claims/v1'; issuer: string; keyId: string; keyGeneration: number; authorityEpoch: number; subject: string; tenant: string; repository: string; permission: 'content.materialize' | 'content.upload'; operation: 'download' | 'upload'; audience: string; issuedAt: number; expiresAt: number; nonce: string; replay: 'single-use' | 'idempotent'; objectIds: string[]; requestRoot: string | null; }
export interface TransferGrantEnvelope { schemaVersion: 'ogvcs.authorization/transfer-grant/v1'; algorithm: 'Ed25519'; keyId: string; claims: TransferGrantClaims; signature: string; }
export interface TransferGrantContext { schemaVersion: 'ogvcs.authorization/transfer-grant-context/v1'; issuer: string; keyId: string; subject: string; permission: 'content.materialize' | 'content.upload'; operation: 'download' | 'upload'; audience: string; tenant: string; repository: string; authorityEpoch: number; keyGeneration: number; now: number; objectId: string; requestObjectIds: string[]; consumedNonces: string[]; }
export interface ThreatVector { schemaVersion: 'ogvcs.authorization/threat-vector/v1'; id: string; abuseCase: string; category: string; kind: 'authorization' | 'authorized-view' | 'transfer-grant' | 'deduplication' | 'sandbox'; input: Record<string, JsonValue>; expected: AuthorizationOutcome; forbiddenResponseFields: string[]; }
export interface ThreatRunnerRow { id: string; status: 'passed' | 'failed'; expectedCode: AuthorizationDecisionCode; actualCode: AuthorizationDecisionCode; }
export interface ThreatRunnerReport { schemaVersion: 'ogvcs.authorization/runner-report/v1'; contractVersion: '1.0.0'; manifestSha256: string; registrySetSha256: string; adapter: 'reference-fixture' | 'external-adapter'; vectors: number; passed: number; failed: number; resultsSha256: string; rows: ThreatRunnerRow[]; }
export interface LoadedAuthorizationContract { readonly manifest: Readonly<Record<string, JsonValue>>; readonly manifestSha256: string; readonly registries: Readonly<Record<string, Readonly<Record<string, JsonValue>>>>; readonly policies: Readonly<Record<string, AuthorizationPolicyFixture>>; readonly vectors: Readonly<Record<string, JsonValue>>; }
export interface ExternalAdapterDescriptor { command: string; args?: string[]; env?: Record<string, string>; }
export interface ThreatRunnerOptions { adapter?: string[] | ExternalAdapterDescriptor; timeoutMs?: number; maxStdoutBytes?: number; maxStderrBytes?: number; maxLineBytes?: number; signal?: unknown; }
export declare const CONTRACT_VERSION: '1.0.0';
export declare const MANIFEST_SHA256: string;
export declare const REGISTRY_SET_SHA256: string;
export declare const REGISTRY_ASSIGNMENT_SHA256: Readonly<Record<string, string>>;
export declare const REGISTRY_NAMES: readonly string[];
export declare const ACTOR_CLASSES: readonly AuthorizationActorClass[];
export declare const CREDENTIAL_CLASSES: readonly AuthorizationCredentialClass[];
export declare const PERMISSIONS: readonly AuthorizationPermission[];
export declare const RESOURCE_TYPES: readonly AuthorizationResourceType[];
export declare const DECISION_CODES: readonly AuthorizationDecisionCode[];
export declare const AUDIT_CLASSES: readonly AuthorizationAuditClass[];
export declare const AUDIT_CLASS_PERMISSIONS: Readonly<Record<AuthorizationAuditClass, AuthorizationPermission>>;
export declare const ERROR_CODES: Readonly<Record<string, AuthorizationContractErrorCode>>;
export declare class AuthorizationContractError extends Error { readonly code: AuthorizationContractErrorCode; readonly exitCode: number; constructor(code: AuthorizationContractErrorCode, message: string, options?: { cause?: unknown; exitCode?: number }); toJSON(): { code: AuthorizationContractErrorCode; message: string }; }
export declare const GRANT_DOMAIN: Uint8Array;
export declare const REQUEST_ROOT_DOMAIN: Uint8Array;
export declare function canonicalJson(value: JsonValue, options?: Record<string, number | boolean>): string;
export declare function canonicalBytes(value: JsonValue, options?: Record<string, number | boolean>): Uint8Array;
export declare function parseCanonicalJson(input: string | Uint8Array, options?: Record<string, number | boolean>): JsonValue;
export declare function sha256(value: string | Uint8Array): string;
export declare function loadAuthorizationContract(): Promise<LoadedAuthorizationContract>;
export declare function evaluateFixturePolicy(policy: AuthorizationPolicyFixture | unknown, request: AuthorizationRequest | unknown): AuthorizationDecision;
export declare function makeFixtureRequest(repository: Record<string, unknown>, id: string, actorId: string, resourceId: string, permission: AuthorizationPermission, overrides?: Record<string, unknown>): AuthorizationRequest;
export declare function authorizationRequestFromFixtureOperation(operation: unknown, bindings?: Record<string, unknown>): AuthorizationRequest;
export declare function signConformanceGrant(claims: TransferGrantClaims | unknown, privateJwk: Record<string, unknown>, options: { conformanceOnly: true }): TransferGrantEnvelope;
export declare function requestRootForObjectIds(objectIds: string[]): string;
export declare function verifyTransferGrant(envelope: TransferGrantEnvelope | unknown, context: TransferGrantContext | unknown, publicJwk: Record<string, unknown>): AuthorizationOutcome;
export declare function buildAuthorizedView(options: { policy: AuthorizationPolicyFixture; repository: Record<string, unknown>; actorId: string; permission: AuthorizationPermission; candidates?: Record<string, JsonValue>[]; pageSize?: number; cursor?: string | null; maxCandidates?: number }): { readonly items: readonly Record<string, JsonValue>[]; readonly nextCursor: string | null };
export declare function evaluateSandboxAttempt(profile: unknown, attempt: unknown): AuthorizationOutcome;
export declare function validateAuthorizationRequest(input: unknown): AuthorizationRequest;
export declare function validateAuthorizationDecision(input: unknown): AuthorizationDecision;
export declare function validateAuditEvent(input: unknown): AuthorizationAuditEvent;
export declare function validatePolicyFixture(input: unknown): AuthorizationPolicyFixture;
export declare function validateTransferGrantClaims(input: unknown): TransferGrantClaims;
export declare function validateTransferGrantEnvelope(input: unknown): TransferGrantEnvelope;
export declare function validateGrantContext(input: unknown): TransferGrantContext;
export declare function validateRequestObjectIds(input: unknown): string[];
export declare function validateThreatVector(input: unknown): ThreatVector;
export declare function validateRunnerResult(input: unknown): { schemaVersion: 'ogvcs.authorization/runner-result/v1'; id: string; result: 'allow' | 'deny'; code: AuthorizationDecisionCode };
export declare function executeReferenceVector(vector: ThreatVector | unknown, contract?: LoadedAuthorizationContract): Promise<AuthorizationOutcome>;
export declare function runThreatVectors(options?: ThreatRunnerOptions): Promise<ThreatRunnerReport>;
